export interface HeritageSite {
  id: string;
  name: string;
  description: string; // Short preview for cards
  overview: string;    // Full informative description
  significance: string; // Historical value
  category: 
    | 'Churches & Religious Heritage Sites'
    | 'Ancestral Houses & Heritage Residences'
    | 'Museums & Cultural Institutions'
    | 'Historical Landmarks & Monuments'
    | 'Plazas, Parks & Public Spaces'
    | 'Government & Historic Buildings'
    | 'Cultural & Religious (Non-Catholic Sites)';
  location: string;
  city: 'Cebu City' | 'Lapu-Lapu City' | 'Mandaue City' | 'Talisay City';
  visitingHours: string;
  imageUrl: string;
  galleryImages?: string[];
  rating: number;
  tags: string[];
  coordinates: {
    lat: number;
    lng: number;
  };
  googleMapsUrl: string;
  isMustVisit: boolean;
  needsVerification?: boolean;
}

export const HERITAGE_SITES: HeritageSite[] = [
  // --- CEBU CITY ---
  {
    id: 'cebu-basilica',
    name: "Basilica Minore del Santo Niño de Cebu",
    description: "The oldest Roman Catholic church in the Philippines, established in 1565.",
    overview: "The Basilica Minore del Santo Niño is the spiritual heart of Cebu. This massive stone structure was established in 1565 by Fray Andres de Urdaneta and Miguel Lopez de Legazpi. The current building, completed in 1739, features a blend of Romanesque and Muslim architectural influences. It is the primary site of devotion for the Santo Niño, the holy child image given by Magellan to Rajah Humabon's wife in 1521.",
    significance: "As the birthplace of Christianity in the Philippines, the Basilica is a National Historical Landmark. It houses the oldest religious relic in the country and serves as the center of the annual Sinulog Festival, a global celebration of Cebuano faith and culture.",
    category: "Churches & Religious Heritage Sites",
    location: "Osmeña Blvd, Cebu City",
    city: "Cebu City",
    visitingHours: "6:00 AM - 8:00 PM",
    imageUrl: "https://picsum.photos/seed/basilica/800/600",
    galleryImages: ["https://picsum.photos/seed/basilica-2/800/600"],
    rating: 4.9,
    tags: ["oldest church", "religious", "sinulog"],
    coordinates: { lat: 10.29419, lng: 123.90212 },
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Basilica+Minore+del+Santo+Nino",
    isMustVisit: true
  },
  {
    id: 'cebu-cathedral',
    name: "Metropolitan Cebu Cathedral",
    description: "The ecclesiastical seat of the Archdiocese of Cebu.",
    overview: "Located just blocks from the Basilica, the Metropolitan Cathedral of the Holy Guardian Angels is a masterpiece of Spanish colonial architecture. Its thick, low-slung walls were designed to withstand earthquakes, and its facade is decorated with traditional relief carvings. It serves as the primary seat of the Catholic Church in the Visayas.",
    significance: "Established as a parish in 1595, it is a testament to the growth of the ecclesiastical administration in the region. It holds the remains of several notable Cebuano bishops and stands as a symbol of the city's enduring religious governance.",
    category: "Churches & Religious Heritage Sites",
    location: "Mabini St, Cebu City",
    city: "Cebu City",
    visitingHours: "5:00 AM - 8:00 PM",
    imageUrl: "https://picsum.photos/seed/cathedral/800/600",
    rating: 4.7,
    tags: ["cathedral", "baroque"],
    coordinates: { lat: 10.29544, lng: 123.90284 },
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Cebu+Metropolitan+Cathedral",
    isMustVisit: false
  },
  {
    id: 'cebu-cross',
    name: "Magellan’s Cross",
    description: "The site where the first Christian cross was planted in 1521.",
    overview: "Housed in an octagonal stone kiosk next to the Basilica, Magellan's Cross is the most iconic symbol of Cebu City. The wooden cross visible to the public is said to contain fragments of the original cross planted by Ferdinand Magellan's expedition on April 14, 1521. The ceiling of the pavilion is adorned with murals depicting the first baptism of the native Filipinos.",
    significance: "This site marks the beginning of the Spanish colonial era and the introduction of Christianity to the archipelago. It is a powerful emblem of the historical encounter between the West and the East in the 16th century.",
    category: "Churches & Religious Heritage Sites",
    location: "P. Burgos St, Cebu City",
    city: "Cebu City",
    visitingHours: "8:00 AM - 6:00 PM",
    imageUrl: "https://picsum.photos/seed/magellan/800/600",
    rating: 4.8,
    tags: ["cross", "magellan"],
    coordinates: { lat: 10.29362, lng: 123.90192 },
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Magellan%27s+Cross",
    isMustVisit: true
  },
  {
    id: 'cebu-archdiocesan-museum',
    name: "Archdiocesan Museum of Cebu",
    description: "A museum showcasing the religious history and artifacts of the Archdiocese.",
    overview: "Located within the Cebu Cathedral complex, this museum is housed in the historic 'Bahay na Bato' that once served as the rectory of the cathedral. It displays a vast collection of ecclesiastical treasures, including century-old vestments, silver altarpieces, and religious statues from various parishes across Cebu.",
    significance: "The museum preserves the material culture of the Catholic faith in Cebu. It provides a rare look at the artistic and historical development of religious practice in the Visayas since the early Spanish period.",
    category: "Churches & Religious Heritage Sites",
    location: "Cathedral Complex, Mabini St, Cebu City",
    city: "Cebu City",
    visitingHours: "9:00 AM - 5:00 PM",
    imageUrl: "https://picsum.photos/seed/archmuseum/800/600",
    rating: 4.5,
    tags: ["museum", "religious-art"],
    coordinates: { lat: 10.2952, lng: 123.9025 },
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Archdiocesan+Museum+of+Cebu",
    isMustVisit: false
  },
  {
    id: 'cebu-casa-gorordo',
    name: "Casa Gorordo Museum",
    description: "A restored 19th-century residence of the Gorordo family.",
    overview: "Casa Gorordo is a classic example of a 'Bahay na Bato' (house of stone) located in the historic Parian district. Built in the mid-19th century, it was once the home of the first Filipino Bishop of Cebu, Juan Gorordo. The house features coral stone ground floors and fine hardwood upper floors, filled with period furniture and artifacts.",
    significance: "This museum provides a window into the lifestyle of the Filipino elite (mestizo) during the 19th century. It highlights the cultural synthesis of Spanish, Chinese, and native influences that defined Cebu's social history.",
    category: "Ancestral Houses & Heritage Residences",
    location: "Lopez Jaena St, Cebu City",
    city: "Cebu City",
    visitingHours: "9:00 AM - 5:00 PM",
    imageUrl: "https://picsum.photos/seed/gorordo/800/600",
    rating: 4.7,
    tags: ["mansion", "lifestyle"],
    coordinates: { lat: 10.29952, lng: 123.90424 },
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Casa+Gorordo+Museum",
    isMustVisit: true
  },
  {
    id: 'cebu-yap-sandiego',
    name: "Yap-Sandiego Ancestral House",
    description: "One of the oldest private residential houses in the Philippines.",
    overview: "Built in the late 17th century, this house is made of coral stones and molave wood. It was built by Chinese merchants and remains one of the few surviving residential structures from that era in the Parian district. The interior is a treasure trove of antiques and curiosities collected by the descendants of the original owners.",
    significance: "It is a rare surviving link to the prosperous Chinese merchant community that thrived in Cebu centuries ago. Its structural integrity and original materials make it a primary artifact of pre-modern urban life in the Philippines.",
    category: "Ancestral Houses & Heritage Residences",
    location: "Mabini St, Parian, Cebu City",
    city: "Cebu City",
    visitingHours: "9:00 AM - 6:00 PM",
    imageUrl: "https://picsum.photos/seed/yap/800/600",
    rating: 4.7,
    tags: ["ancestral", "parian"],
    coordinates: { lat: 10.29871, lng: 123.90342 },
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Yap-Sandiego+Ancestral+House",
    isMustVisit: true
  },
  {
    id: 'cebu-jesuit-house',
    name: "1730 Jesuit House",
    description: "A historic 18th-century structure tucked away in a modern warehouse.",
    overview: "Located deep within a modern hardware warehouse in Parian, this house dates back to 1730. It once served as the residence of the Jesuit Superior in Cebu. The house features massive coral walls and a traditional roof structure that has survived for nearly 300 years.",
    significance: "As one of the oldest dated residences in the country, it offers unique insights into the architectural transitions of the early 18th century and the historical presence of the Jesuit order in the Visayas.",
    category: "Ancestral Houses & Heritage Residences",
    location: "Zulueta St, Cebu City",
    city: "Cebu City",
    visitingHours: "9:00 AM - 11:30 AM, 1:30 PM - 4:30 PM",
    imageUrl: "https://picsum.photos/seed/jesuit/800/600",
    rating: 4.6,
    tags: ["jesuit", "hidden-gem"],
    coordinates: { lat: 10.2984, lng: 123.9036 },
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=1730+Jesuit+House",
    isMustVisit: false
  },
  {
    id: 'cebu-national-museum',
    name: "National Museum of the Philippines – Cebu",
    description: "Housed in the historic Aduana (Customhouse) building.",
    overview: "Located near the port area, the National Museum of the Philippines – Cebu is housed in the neoclassical Aduana Building, also known as Malacañang sa Sugbo. The museum features various galleries dedicated to Cebu's archaeological finds, ethnographic history, and fine arts.",
    significance: "The building itself is a landmark of American colonial architecture. As a museum, it serves as the central repository for the cultural and natural heritage of the Visayas, showcasing the island's deep historical roots.",
    category: "Museums & Cultural Institutions",
    location: "A. Pigafetta St, Cebu City",
    city: "Cebu City",
    visitingHours: "9:00 AM - 6:00 PM",
    imageUrl: "https://picsum.photos/seed/natmuseum/800/600",
    rating: 4.8,
    tags: ["museum", "aduana"],
    coordinates: { lat: 10.2925, lng: 123.9055 },
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=National+Museum+Cebu",
    isMustVisit: true
  },
  {
    id: 'cebu-halad-museum',
    name: "Jose R. Gullas Halad Museum",
    description: "A museum dedicated to the musical heritage of Cebu.",
    overview: "This museum pays tribute to the composers and musicians of Cebu. It displays musical scores, traditional instruments, and memorabilia of the golden age of Cebuano music. It is a unique destination for those interested in the 'Harana' and 'Visayan Love Song' traditions.",
    significance: "It preserves the intangible heritage of Cebuano music, ensuring that the contributions of local artists to the Philippine cultural landscape are remembered and celebrated.",
    category: "Museums & Cultural Institutions",
    location: "D. Jakosalem St, Cebu City",
    city: "Cebu City",
    visitingHours: "9:00 AM - 5:00 PM",
    imageUrl: "https://picsum.photos/seed/halad/800/600",
    rating: 4.5,
    tags: ["music", "culture"],
    coordinates: { lat: 10.2965, lng: 123.9032 },
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Jose+R.+Gullas+Halad+Museum",
    isMustVisit: false
  },
  {
    id: 'cebu-usc-museum',
    name: "University of San Carlos Museum",
    description: "An academic museum with extensive archaeological and ethnographic collections.",
    overview: "Located within the USC Main Campus, this museum features four main galleries: Archaeological, Ethnological, Biological, and Ceramics. It is one of the most comprehensive university museums in the country, showcasing artifacts from the pre-colonial era to the present.",
    significance: "The USC Museum is a center for academic research and cultural preservation. Its collections highlight the sophistication of early Philippine societies and their extensive trade networks with mainland Asia.",
    category: "Museums & Cultural Institutions",
    location: "P. del Rosario St, Cebu City",
    city: "Cebu City",
    visitingHours: "8:30 AM - 5:30 PM",
    imageUrl: "https://picsum.photos/seed/uscmuseum/800/600",
    rating: 4.6,
    tags: ["academic", "artifacts"],
    coordinates: { lat: 10.2998, lng: 123.8988 },
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=USC+Museum+Cebu",
    isMustVisit: false
  },
  {
    id: 'cebu-fort-san-pedro',
    name: "Fort San Pedro",
    description: "The oldest and smallest bastion fort in the Philippines.",
    overview: "Built in 1565 by Miguel Lopez de Legazpi, this triangular bastion fort served as a military defense structure for the first Spanish settlement. It is made of coral stones and features three bastions: La Concepcion, Ignacio de Loyola, and San Miguel. Today, it is a quiet park with a small museum.",
    significance: "It is a symbol of early Spanish military presence in Asia. Its surviving walls tell the story of Cebu's evolution from a defensive outpost to a bustling trade city.",
    category: "Historical Landmarks & Monuments",
    location: "A. Pigafetta St, Cebu City",
    city: "Cebu City",
    visitingHours: "8:00 AM - 7:00 PM",
    imageUrl: "https://picsum.photos/seed/fort/800/600",
    rating: 4.6,
    tags: ["military", "bastion"],
    coordinates: { lat: 10.29242, lng: 123.90562 },
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Fort+San+Pedro",
    isMustVisit: true
  },
  {
    id: 'cebu-heritage-monument',
    name: "Heritage of Cebu Monument",
    description: "A massive bronze sculpture depicting the history of Cebu.",
    overview: "Located in Plaza Parian, this monumental sculpture by Edgardo Castrillo depicts major historical events in Cebu, including the Battle of Mactan, the canonization of St. Pedro Calungsod, and the first baptism. The monument is made of dark bronze and stone, standing as a permanent history book in the middle of a busy street.",
    significance: "It serves as a collective memory of the Cebuano people, visually summarizing the pivotal moments that shaped the island's identity over five centuries.",
    category: "Historical Landmarks & Monuments",
    location: "Plaza Parian, Mabini St, Cebu City",
    city: "Cebu City",
    visitingHours: "24 Hours",
    imageUrl: "https://picsum.photos/seed/heritagemonument/800/600",
    rating: 4.7,
    tags: ["sculpture", "parian"],
    coordinates: { lat: 10.2988, lng: 123.9033 },
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Heritage+of+Cebu+Monument",
    isMustVisit: true
  },
  {
    id: 'cebu-colon-street',
    name: "Colon Street & Historical Marker",
    description: "The oldest national road in the Philippines.",
    overview: "Named after Cristobal Colon (Christopher Columbus), this street was developed by the Spanish in the 16th century. It was once the center of Cebu's social and commercial life. Today, an obelisk and historical marker stand at its end to commemorate its status as the country's oldest street.",
    significance: "Colon Street is a living landmark of urban planning and commercial history. It represents the enduring spirit of Cebuano trade and resilience through centuries of change.",
    category: "Historical Landmarks & Monuments",
    location: "Colon St, Cebu City",
    city: "Cebu City",
    visitingHours: "24 Hours",
    imageUrl: "https://picsum.photos/seed/colon/800/600",
    rating: 4.3,
    tags: ["oldest-street", "commercial"],
    coordinates: { lat: 10.2975, lng: 123.9028 },
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Colon+Street+Marker",
    isMustVisit: false
  },
  {
    id: 'cebu-plaza-independencia',
    name: "Plaza Independencia",
    description: "A grand historic plaza near Fort San Pedro.",
    overview: "Plaza Independencia is a large public square that has served as a center for social and political gatherings since the Spanish period. It features century-old acacia trees, well-manicured gardens, and several monuments dedicated to national and local heroes.",
    significance: "It is a symbol of Cebuano freedom and public life. Its proximity to the fort and the port makes it a historic gateway for all who visit the city.",
    category: "Plazas, Parks & Public Spaces",
    location: "M.J. Cuenco Ave, Cebu City",
    city: "Cebu City",
    visitingHours: "24 Hours",
    imageUrl: "https://picsum.photos/seed/independencia/800/600",
    rating: 4.5,
    tags: ["plaza", "park"],
    coordinates: { lat: 10.2928, lng: 123.9052 },
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Plaza+Independencia+Cebu",
    isMustVisit: true
  },
  {
    id: 'cebu-plaza-sugbo',
    name: "Plaza Sugbo",
    description: "The plaza fronting Magellan's Cross and City Hall.",
    overview: "This open space is the primary staging area for many of Cebu City's civic ceremonies. It is situated between Magellan's Cross and the Cebu City Hall, serving as a connector for the city's religious and political centers.",
    significance: "Significant as the site of the original foundation of the city's civic center. It is a popular spot for photography and public events, maintaining its role as the 'front yard' of Cebu City.",
    category: "Plazas, Parks & Public Spaces",
    location: "Magallanes St, Cebu City",
    city: "Cebu City",
    visitingHours: "24 Hours",
    imageUrl: "https://picsum.photos/seed/sugbo/800/600",
    rating: 4.4,
    tags: ["plaza", "civic"],
    coordinates: { lat: 10.2938, lng: 123.9018 },
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Plaza+Sugbo",
    isMustVisit: false
  },
  {
    id: 'cebu-plaza-hamabar',
    name: "Plaza Hamabar",
    description: "A plaza dedicated to Rajah Humabon, the native ruler of Cebu.",
    overview: "Located near the Cathedral, this plaza features a statue of Rajah Humabon, the first native ruler to be baptized in 1521. It is a quiet, shaded area that honors the pre-colonial leadership of the island.",
    significance: "It commemorates the native roots of Cebuano leadership and the initial encounter between the local nobility and the Spanish expedition.",
    category: "Plazas, Parks & Public Spaces",
    location: "Mabini St, Cebu City",
    city: "Cebu City",
    visitingHours: "24 Hours",
    imageUrl: "https://picsum.photos/seed/hamabar/800/600",
    rating: 4.2,
    tags: ["rajah", "history"],
    coordinates: { lat: 10.2951, lng: 123.9022 },
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Plaza+Hamabar",
    isMustVisit: false
  },
  {
    id: 'cebu-fuente-osmena',
    name: "Fuente Osmeña Circle",
    description: "An iconic rotunda and fountain honoring Sergio Osmeña.",
    overview: "Located at the heart of Cebu City's uptown area, Fuente Osmeña is a circular park with a grand fountain at its center. It was built in 1912 to mark the opening of the city's water system and is named after Cebu's most famous son, President Sergio Osmeña.",
    significance: "It is a symbol of the modernization of Cebu during the American period. Today, it remains a focal point for city celebrations, especially during the Sinulog season.",
    category: "Plazas, Parks & Public Spaces",
    location: "Osmeña Blvd, Cebu City",
    city: "Cebu City",
    visitingHours: "24 Hours",
    imageUrl: "https://picsum.photos/seed/fuente/800/600",
    rating: 4.5,
    tags: ["fountain", "osmeña"],
    coordinates: { lat: 10.3113, lng: 123.8928 },
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Fuente+Osmena+Circle",
    isMustVisit: false
  },
  {
    id: 'cebu-city-hall',
    name: "Cebu City Hall",
    description: "The seat of the local government of Cebu City.",
    overview: "The Cebu City Hall is a prominent administrative building located in the heart of the heritage district. The current structure stands on the site of previous town halls, overlooking Plaza Sugbo and Magellan's Cross.",
    significance: "It represents the administrative heart of the oldest city in the Philippines, facilitating the governance of a rapidly growing metropolis while preserving its historical surroundings.",
    category: "Government & Historic Buildings",
    location: "M.C. Briones St, Cebu City",
    city: "Cebu City",
    visitingHours: "8:00 AM - 5:00 PM",
    imageUrl: "https://picsum.photos/seed/cityhall/800/600",
    rating: 4.1,
    tags: ["government", "civic"],
    coordinates: { lat: 10.29312, lng: 123.90151 },
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Cebu+City+Hall",
    isMustVisit: false
  },
  {
    id: 'cebu-capitol',
    name: "Cebu Provincial Capitol",
    description: "A neoclassical masterpiece and seat of the provincial government.",
    overview: "Designed by Juan Arellano and completed in 1938, the Capitol is a grand neoclassical building with a central dome. It is considered one of the most beautiful government buildings in the country, featuring ornate interiors and historic murals.",
    significance: "A protected National Historical Landmark, it symbolizes the political importance of Cebu province and is a premier example of American-era architecture in the Philippines.",
    category: "Government & Historic Buildings",
    location: "Escario St, Cebu City",
    city: "Cebu City",
    visitingHours: "8:00 AM - 5:00 PM",
    imageUrl: "https://picsum.photos/seed/capitol/800/600",
    rating: 4.8,
    tags: ["capitol", "neoclassical"],
    coordinates: { lat: 10.31752, lng: 123.89062 },
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Cebu+Provincial+Capitol",
    isMustVisit: true
  },
  {
    id: 'cebu-patria',
    name: "Patria de Cebu",
    description: "A historic Catholic center and commercial building.",
    overview: "Located across from the Cathedral, Patria de Cebu has served for decades as a community center for the Catholic youth. The original structure features classic mid-20th-century architecture and is currently being integrated into a new development.",
    significance: "It is a landmark of the Catholic Church's social mission in Cebu, serving as a hub for various religious and civic activities for generations.",
    category: "Government & Historic Buildings",
    location: "P. Burgos St, Cebu City",
    city: "Cebu City",
    visitingHours: "Daylight Hours",
    imageUrl: "https://picsum.photos/seed/patria/800/600",
    rating: 4.0,
    tags: ["catholic", "commercial"],
    coordinates: { lat: 10.2945, lng: 123.9024 },
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Patria+de+Cebu",
    isMustVisit: false
  },
  {
    id: 'cebu-taoist',
    name: "Cebu Taoist Temple",
    description: "A colorful temple and cultural landmark of the Chinese community.",
    overview: "Built in 1972, this multi-tiered temple sits high in Beverly Hills. It features vibrant dragons, pagodas, and a replica of the Great Wall. It is the center of worship for the Taoist community in Cebu.",
    significance: "It highlights the deep Chinese-Cebuano heritage and the religious diversity of the island. It offers one of the best panoramic views of the city.",
    category: "Cultural & Religious (Non-Catholic Sites)",
    location: "Beverly Hills, Cebu City",
    city: "Cebu City",
    visitingHours: "8:00 AM - 5:00 PM",
    imageUrl: "https://picsum.photos/seed/taoist/800/600",
    rating: 4.6,
    tags: ["temple", "chinese"],
    coordinates: { lat: 10.33442, lng: 123.88831 },
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Cebu+Taoist+Temple",
    isMustVisit: true
  },

  // --- TALISAY CITY ---
  {
    id: 'talisay-landing',
    name: "Talisay Landing Site",
    description: "The site of the American liberation landing in 1945.",
    overview: "Larawan Beach in Talisay is the historic site where American forces landed on March 26, 1945, to begin the liberation of Cebu from Japanese occupation. A monument with life-sized statues commemorates the event.",
    significance: "This site is a major WWII landmark, symbolizing the shared history and alliance between the Philippines and the US. It is the site of annual liberation celebrations.",
    category: "Historical Landmarks & Monuments",
    location: "Larawan Beach, Talisay City",
    city: "Talisay City",
    visitingHours: "24 Hours",
    imageUrl: "https://picsum.photos/seed/talisay-landing/800/600",
    rating: 4.6,
    tags: ["WWII", "memorial"],
    coordinates: { lat: 10.25251, lng: 123.84452 },
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Talisay+Landing+Site",
    isMustVisit: true
  },
  {
    id: 'talisay-church',
    name: "Sta. Teresa de Avila Parish Church",
    description: "A historic church dedicated to St. Teresa of Avila.",
    overview: "This parish church is a focal point of Talisay's religious life. Built in the classic style with sturdy walls, it has undergone various renovations but maintains its spiritual importance to the community.",
    significance: "It is the religious center of the city and reflects the long-standing Catholic traditions of Talisay, serving as a landmark for the city's historical growth.",
    category: "Churches & Religious Heritage Sites",
    location: "Poblacion, Talisay City",
    city: "Talisay City",
    visitingHours: "6:00 AM - 7:00 PM",
    imageUrl: "https://picsum.photos/seed/talisay-church/800/600",
    rating: 4.5,
    tags: ["church", "religious"],
    coordinates: { lat: 10.2442, lng: 123.8475 },
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Sta.+Teresa+de+Avila+Parish+Church+Talisay",
    isMustVisit: false
  },
  {
    id: 'talisay-plaza',
    name: "Talisay City Plaza",
    description: "The main public space in the heart of Talisay.",
    overview: "The Talisay City Plaza is a wide open space where residents gather for recreation and civic events. It is surrounded by the church and old government buildings.",
    significance: "It serves as the 'living room' of the city, representing the community-centric culture of Talisay and its heritage as a coastal town.",
    category: "Plazas, Parks & Public Spaces",
    location: "Poblacion, Talisay City",
    city: "Talisay City",
    visitingHours: "24 Hours",
    imageUrl: "https://picsum.photos/seed/talisay-plaza/800/600",
    rating: 4.2,
    tags: ["plaza", "civic"],
    coordinates: { lat: 10.2435, lng: 123.8480 },
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Talisay+City+Plaza",
    isMustVisit: false
  },
  {
    id: 'talisay-city-hall',
    name: "Talisay City Hall",
    description: "The administrative center of Talisay City.",
    overview: "The Talisay City Hall is a modern building that serves as the administrative hub of the city, managing its rapid urban development while honoring its historical roots.",
    significance: "It represents the administrative progress of Talisay from a municipality to a component city of Metro Cebu.",
    category: "Government & Historic Buildings",
    location: "Biasong-Dumlog, Talisay City",
    city: "Talisay City",
    visitingHours: "8:00 AM - 5:00 PM",
    imageUrl: "https://picsum.photos/seed/talisay-cityhall/800/600",
    rating: 4.1,
    tags: ["government", "civic"],
    coordinates: { lat: 10.2482, lng: 123.8395 },
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Talisay+City+Hall",
    isMustVisit: false
  },

  // --- MANDAUE CITY ---
  {
    id: 'mandaue-church',
    name: "National Shrine of Saint Joseph",
    description: "The historic mother church of Mandaue City.",
    overview: "The National Shrine of Saint Joseph is a large stone church located in the heart of Mandaue. It was established by the Jesuits in 1601 and has survived various calamities. It is famous for its large statues of the Holy Family.",
    significance: "It is the spiritual center of Mandaue and a National Shrine. It is the site of the 'Traslacion' during the Sinulog festival, representing the unity of the church in Metro Cebu.",
    category: "Churches & Religious Heritage Sites",
    location: "P. Burgos St, Mandaue City",
    city: "Mandaue City",
    visitingHours: "5:00 AM - 8:00 PM",
    imageUrl: "https://picsum.photos/seed/mandaue-church/800/600",
    rating: 4.8,
    tags: ["shrine", "religious"],
    coordinates: { lat: 10.3305, lng: 123.9385 },
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=National+Shrine+of+Saint+Joseph+Mandaue",
    isMustVisit: true
  },
  {
    id: 'mandaue-monastery',
    name: "Our Lady of the Sacred Heart Church",
    description: "A peaceful church and monastery in Mandaue.",
    overview: "Also known as the Monastery of the Holy Eucharist, this church offers a serene environment for prayer and reflection, tucked away from the city's industrial noise.",
    significance: "It is a center for contemplative life and devotion, serving as a spiritual oasis for the residents of Mandaue.",
    category: "Churches & Religious Heritage Sites",
    location: "Mandaue City",
    city: "Mandaue City",
    visitingHours: "Daylight Hours",
    imageUrl: "https://picsum.photos/seed/mandaue-monastery/800/600",
    rating: 4.5,
    tags: ["monastery", "quiet"],
    coordinates: { lat: 10.3450, lng: 123.9510 },
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Our+Lady+of+the+Sacred+Heart+Church+Mandaue",
    isMustVisit: false
  },
  {
    id: 'mandaue-suico-house',
    name: "Suico Ancestral House",
    description: "A well-preserved heritage residence in Mandaue.",
    overview: "The Suico Ancestral House is a private residence that showcases the architectural style of a bygone era in Mandaue, with classic wooden features and historic charm.",
    significance: "It is one of the few remaining ancestral homes in Mandaue that highlights the city's residential heritage and social history.",
    category: "Ancestral Houses & Heritage Residences",
    location: "Mandaue City",
    city: "Mandaue City",
    visitingHours: "Private Property / By Appointment",
    imageUrl: "https://picsum.photos/seed/suico-house/800/600",
    rating: 4.2,
    tags: ["ancestral", "private"],
    coordinates: { lat: 10.3320, lng: 123.9395 },
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Suico+Ancestral+House+Mandaue",
    isMustVisit: false
  },
  {
    id: 'mandaue-cabrera-museum',
    name: "Luis Cabrera Ancestral House and Museum",
    description: "A historic house turned into a cultural museum.",
    overview: "This heritage house preserves the legacy of the Cabrera family and serves as a museum for local Mandaue history and art.",
    significance: "It is a vital cultural institution in Mandaue, providing a space for the preservation of local stories and artifacts.",
    category: "Ancestral Houses & Heritage Residences",
    location: "Mandaue City",
    city: "Mandaue City",
    visitingHours: "By Appointment",
    imageUrl: "https://picsum.photos/seed/cabrera-museum/800/600",
    rating: 4.4,
    tags: ["museum", "ancestral"],
    coordinates: { lat: 10.3295, lng: 123.9370 },
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Luis+Cabrera+Ancestral+House+Mandaue",
    isMustVisit: false
  },
  {
    id: 'mandaue-quijano-museum',
    name: "Quijano Museum",
    description: "A private museum showcasing local heritage items.",
    overview: "The Quijano Museum holds various artifacts and memorabilia that reflect the life and times of Mandaue's past generations.",
    significance: "Significant as an archival repository for the city's personal and public histories.",
    category: "Museums & Cultural Institutions",
    location: "Mandaue City",
    city: "Mandaue City",
    visitingHours: "By Appointment",
    imageUrl: "https://picsum.photos/seed/quijano-museum/800/600",
    rating: 4.3,
    tags: ["museum", "private"],
    coordinates: { lat: 10.3280, lng: 123.9360 },
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Quijano+Museum+Mandaue",
    isMustVisit: false
  },
  {
    id: 'mandaue-library',
    name: "Mandaue City Public Library",
    description: "A historic library known for its spiral staircase.",
    overview: "The Mandaue City Public Library is an important educational resource that also holds architectural value, specifically its historic spiral staircase.",
    significance: "It serves as a hub for learning and a guardian of the city's intellectual heritage.",
    category: "Museums & Cultural Institutions",
    location: "Poblacion, Mandaue City",
    city: "Mandaue City",
    visitingHours: "8:00 AM - 5:00 PM",
    imageUrl: "https://picsum.photos/seed/mandaue-library/800/600",
    rating: 4.2,
    tags: ["library", "educational"],
    coordinates: { lat: 10.3315, lng: 123.9400 },
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Mandaue+City+Public+Library",
    isMustVisit: false
  },
  {
    id: 'mandaue-watchtower',
    name: "Bantayan sa Hari",
    description: "A Spanish-era watchtower used for coastal defense.",
    overview: "The Bantayan sa Hari is a stone watchtower that was once used to spot marauding pirates. Its ruins stand as a reminder of the coastal defense system of Cebu.",
    significance: "It is a rare surviving example of pre-modern military architecture in Mandaue, symbolizing the city's role in the regional defense network.",
    category: "Historical Landmarks & Monuments",
    location: "Looc, Mandaue City",
    city: "Mandaue City",
    visitingHours: "Daylight Hours",
    imageUrl: "https://picsum.photos/seed/bantayan/800/600",
    rating: 4.0,
    tags: ["watchtower", "spanish"],
    coordinates: { lat: 10.3185, lng: 123.9620 },
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Bantayan+sa+Hari+Mandaue",
    isMustVisit: false
  },
  {
    id: 'mandaue-presidencia',
    name: "Mandaue Presidencia",
    description: "The historic city hall building of Mandaue.",
    overview: "Completed in 1937, this Commonwealth-era building is a landmark of Mandaue's civic identity. It features neoclassical elements and is the heart of the Heritage Plaza.",
    significance: "It is the symbolic seat of power in Mandaue and a protected heritage building, representing the city's administrative continuity.",
    category: "Historical Landmarks & Monuments",
    location: "Poblacion, Mandaue City",
    city: "Mandaue City",
    visitingHours: "8:00 AM - 5:00 PM",
    imageUrl: "https://picsum.photos/seed/mandaue-presidencia/800/600",
    rating: 4.6,
    tags: ["government", "neoclassical"],
    coordinates: { lat: 10.33041, lng: 123.93882 },
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Mandaue+Presidencia",
    isMustVisit: true
  },
  {
    id: 'mandaue-bridge',
    name: "Mandaue-Mactan Bridge",
    description: "The first bridge connecting mainland Cebu to Mactan Island.",
    overview: "Completed in 1972, this bridge was the first permanent link between the mainland and Mactan. It offers iconic views of the channel.",
    significance: "Significant as an engineering feat that transformed the economy of Metro Cebu, linking the industrial hub to the international airport.",
    category: "Historical Landmarks & Monuments",
    location: "Mandaue City",
    city: "Mandaue City",
    visitingHours: "24 Hours",
    imageUrl: "https://picsum.photos/seed/mandaue-bridge/800/600",
    rating: 4.4,
    tags: ["bridge", "iconic"],
    coordinates: { lat: 10.32451, lng: 123.94821 },
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Mandaue+Mactan+Bridge",
    isMustVisit: false
  },
  {
    id: 'mandaue-plaza',
    name: "Mandaue City Heritage Plaza",
    description: "A wide open space in front of the Presidencia.",
    overview: "This plaza is the primary public space of Mandaue, designed to highlight the city's historical landmarks.",
    significance: "It is the focal point for Mandaue's public life and a site for major city events.",
    category: "Plazas, Parks & Public Spaces",
    location: "Poblacion, Mandaue City",
    city: "Mandaue City",
    visitingHours: "24 Hours",
    imageUrl: "https://picsum.photos/seed/mandaue-plaza/800/600",
    rating: 4.3,
    tags: ["plaza", "civic"],
    coordinates: { lat: 10.3302, lng: 123.9390 },
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Mandaue+City+Heritage+Plaza",
    isMustVisit: false
  },
  {
    id: 'mandaue-legislative',
    name: "Mandaue Legislative Building",
    description: "The modern home of the city's council.",
    overview: "Located within the city hall complex, this building manages the city's legislative affairs.",
    significance: "It represents the ongoing growth and modern governance of Mandaue City.",
    category: "Government & Historic Buildings",
    location: "Mandaue City Hall Complex",
    city: "Mandaue City",
    visitingHours: "8:00 AM - 5:00 PM",
    imageUrl: "https://picsum.photos/seed/mandaue-legis/800/600",
    rating: 4.1,
    tags: ["government", "legislative"],
    coordinates: { lat: 10.3308, lng: 123.9392 },
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Mandaue+Legislative+Building",
    isMustVisit: false
  },

  // --- LAPU-LAPU CITY ---
  {
    id: 'llc-shrine',
    name: "Virgen de la Regla National Shrine",
    description: "A major pilgrimage site in Lapu-Lapu City.",
    overview: "This shrine is dedicated to Our Lady of the Rule (Virgen de la Regla). It is a center of deep devotion for the people of Mactan, attracting thousands of pilgrims annually.",
    significance: "It is a focal point of Mactan's spiritual identity and a symbol of the deep-rooted faith of the Oponganons.",
    category: "Churches & Religious Heritage Sites",
    location: "B.M. Dimataga St, Lapu-Lapu City",
    city: "Lapu-Lapu City",
    visitingHours: "5:00 AM - 8:00 PM",
    imageUrl: "https://picsum.photos/seed/llc-shrine/800/600",
    rating: 4.8,
    tags: ["shrine", "pilgrimage"],
    coordinates: { lat: 10.3148, lng: 123.9488 },
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Virgen+de+la+Regla+National+Shrine",
    isMustVisit: true
  },
  {
    id: 'llc-church',
    name: "Our Lady of the Rule Church",
    description: "The historic parish church of Opon.",
    overview: "This church serves the historic parish of Opon (now Lapu-Lapu City) and is integrated with the National Shrine.",
    significance: "Significant as the religious anchor of the island since the Spanish era.",
    category: "Churches & Religious Heritage Sites",
    location: "Lapu-Lapu City",
    city: "Lapu-Lapu City",
    visitingHours: "6:00 AM - 7:00 PM",
    imageUrl: "https://picsum.photos/seed/llc-church/800/600",
    rating: 4.6,
    tags: ["church", "religious"],
    coordinates: { lat: 10.3145, lng: 123.9490 },
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Our+Lady+of+the+Rule+Church",
    isMustVisit: false
  },
  {
    id: 'llc-happyworld',
    name: "Cebu Happy World Museum",
    description: "A fun and interactive 3D art museum.",
    overview: "Cebu Happy World Museum features more than 70 interactive 3D paintings that allow visitors to become part of the art.",
    significance: "A modern cultural institution that offers a creative space for the community and tourists.",
    category: "Museums & Cultural Institutions",
    location: "Cordova - Lapu-Lapu City",
    city: "Lapu-Lapu City",
    visitingHours: "9:00 AM - 6:00 PM",
    imageUrl: "https://picsum.photos/seed/happyworld/800/600",
    rating: 4.5,
    tags: ["museum", "interactive"],
    coordinates: { lat: 10.2355, lng: 123.9555 },
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Cebu+Happy+World+Museum",
    isMustVisit: false
  },
  {
    id: 'llc-mactan-shrine',
    name: "Mactan Shrine",
    description: "Commemorates the Battle of Mactan in 1521.",
    overview: "Located in Punta Engaño, this park commemorates the battle where Lapu-Lapu defeated Magellan. It features the Lapu-Lapu monument and the Magellan Marker.",
    significance: "It is a powerful symbol of Filipino bravery and the first resistance against European colonization.",
    category: "Historical Landmarks & Monuments",
    location: "Punta Engaño Rd, Lapu-Lapu City",
    city: "Lapu-Lapu City",
    visitingHours: "24 Hours",
    imageUrl: "https://picsum.photos/seed/mactan/800/600",
    rating: 4.8,
    tags: ["hero", "battle"],
    coordinates: { lat: 10.33471, lng: 124.01502 },
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Mactan+Shrine",
    isMustVisit: true
  },
  {
    id: 'llc-magellan-marker',
    name: "Magellan’s Marker",
    description: "A stone obelisk honoring the fallen explorer Ferdinand Magellan.",
    overview: "Located within the Mactan Shrine complex, this marker was built by the Spanish in 1866 to honor Magellan on the spot where he is believed to have died.",
    significance: "It represents the dual history of the site—honoring both the native hero and the European explorer who brought the world to the archipelago.",
    category: "Historical Landmarks & Monuments",
    location: "Mactan Shrine, Lapu-Lapu City",
    city: "Lapu-Lapu City",
    visitingHours: "24 Hours",
    imageUrl: "https://picsum.photos/seed/magellan-marker/800/600",
    rating: 4.6,
    tags: ["magellan", "obelisk"],
    coordinates: { lat: 10.3348, lng: 124.0151 },
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Magellans+Marker+Lapu-Lapu",
    isMustVisit: false
  },
  {
    id: 'llc-plaza-rizal',
    name: "Plaza Rizal (Rizal Park)",
    description: "The central public park of Lapu-Lapu City.",
    overview: "A community park featuring a monument to Dr. Jose Rizal, located near the city hall and the church.",
    significance: "It is the civic heart of the city, serving as a venue for local gatherings and national holidays.",
    category: "Plazas, Parks & Public Spaces",
    location: "Poblacion, Lapu-Lapu City",
    city: "Lapu-Lapu City",
    visitingHours: "24 Hours",
    imageUrl: "https://picsum.photos/seed/llc-plaza/800/600",
    rating: 4.2,
    tags: ["plaza", "rizal"],
    coordinates: { lat: 10.3155, lng: 123.9485 },
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Plaza+Rizal+Lapu-Lapu",
    isMustVisit: false
  },
  {
    id: 'llc-millennium-park',
    name: "Millennium Park",
    description: "A coastal park near the bridge area.",
    overview: "Millennium Park offers a refreshing open space with views of the Mactan Channel.",
    significance: "It represents the urban beautification efforts of the city for the new millennium.",
    category: "Plazas, Parks & Public Spaces",
    location: "Pajo, Lapu-Lapu City",
    city: "Lapu-Lapu City",
    visitingHours: "24 Hours",
    imageUrl: "https://picsum.photos/seed/millennium/800/600",
    rating: 4.1,
    tags: ["park", "coastal"],
    coordinates: { lat: 10.3225, lng: 123.9515 },
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Millennium+Park+Lapu-Lapu",
    isMustVisit: false
  },
  {
    id: 'llc-bridge-park',
    name: "Old Bridge Park",
    description: "A park located under the First Mandaue-Mactan Bridge.",
    overview: "This park provides a unique vantage point under the first bridge, popular for its views and community activities.",
    significance: "It transforms an industrial space into a community landmark.",
    category: "Plazas, Parks & Public Spaces",
    location: "Pajo, Lapu-Lapu City",
    city: "Lapu-Lapu City",
    visitingHours: "24 Hours",
    imageUrl: "https://picsum.photos/seed/bridgepark/800/600",
    rating: 4.0,
    tags: ["park", "bridge"],
    coordinates: { lat: 10.3240, lng: 123.9475 },
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Old+Bridge+Park+Lapu-Lapu",
    isMustVisit: false
  }
];

export function getSiteById(id: string) {
  return HERITAGE_SITES.find(site => site.id === id);
}

export function searchSites(query: string, city?: string, category?: string) {
  return HERITAGE_SITES.filter(site => {
    const matchesQuery = query ? (
      site.name.toLowerCase().includes(query.toLowerCase()) ||
      site.description.toLowerCase().includes(query.toLowerCase()) ||
      site.overview.toLowerCase().includes(query.toLowerCase()) ||
      site.significance.toLowerCase().includes(query.toLowerCase()) ||
      site.tags.some(tag => tag.toLowerCase().includes(query.toLowerCase()))
    ) : true;
    
    const matchesCity = city && city !== 'All' ? site.city === city : true;
    const matchesCategory = category && category !== 'All' ? site.category === category : true;
    
    return matchesQuery && matchesCity && matchesCategory;
  });
}
