export interface HeritageSite {
  id: string;
  name: string;
  description: string; // Short preview for cards
  overview: string;    // Full informative description
  significance: string; // Historical value
  category: 
    | 'Churches & Religious Heritage Sites'
    | 'Ancestral Houses & Heritage Residences'
    | 'Museums & Cultural Institutions'
    | 'Historical Landmarks & Monuments'
    | 'Plazas, Parks & Public Spaces'
    | 'Government & Historic Buildings'
    | 'Cultural & Religious (Non-Catholic Sites)';
  location: string;
  city: 'Cebu City' | 'Lapu-Lapu City' | 'Mandaue City' | 'Talisay City';
  visitingHours: string;
  imageUrl: string;
  galleryImages?: string[];
  rating: number;
  tags: string[];
  coordinates: {
    lat: number;
    lng: number;
  };
  googleMapsUrl: string;
  isMustVisit: boolean;
  needsVerification?: boolean;
}

export const HERITAGE_SITES: HeritageSite[] = [
  // --- CEBU CITY ---
  {
    id: 'cebu-basilica',
    name: "Basilica Minore del Santo Niño de Cebu",
    description: "The oldest Roman Catholic church in the Philippines, home to the miraculous image of the Santo Niño.",
    overview: "The Basilica Minore del Santo Niño is a massive stone structure located in the heart of Cebu City. Established in 1565 by Fray Andres de Urdaneta and Miguel Lopez de Legazpi, the current church building was completed in 1739. Visitors can expect to see a blend of Romanesque, Muslim, and Neoclassical architectural styles, featuring thick coral stone walls and a beautifully ornate interior. The complex includes a museum and a grand pilgrim center where thousands of devotees gather every Friday and during the Sinulog festival.\n\nThe church houses the original statue of the Santo Niño, a gift from Ferdinand Magellan to Queen Juana in 1521. This sacred icon is considered the oldest religious relic in the Philippines and is displayed in a side chapel where pilgrims line up for hours to pay their respects. The atmosphere is one of deep devotion, filled with the scent of burning candles and the traditional Sinulog prayer dances performed by candle sellers outside.",
    significance: "Historically, the Basilica marks the birthplace of Christianity in the Far East. It was built on the spot where the image of the Santo Niño was found preserved in a pine box, an event seen as miraculous by the early Spanish explorers. This site represents the successful establishment of Spanish influence and the Catholic faith in the archipelago, serving as the spiritual mother of all churches in the Philippines.\n\nCulturally, the Basilica is the epicenter of the Sinulog Festival, the country's grandest cultural celebration. It serves as a unifying symbol for Cebuanos, representing their resilience through centuries of colonial rule, wars, and natural disasters. The site is a National Historical Landmark and a cornerstone of the nation's intangible heritage.",
    category: "Churches & Religious Heritage Sites",
    location: "Osmeña Blvd, Cebu City",
    city: "Cebu City",
    visitingHours: "6:00 AM - 8:00 PM",
    imageUrl: "https://picsum.photos/seed/basilica/800/600",
    galleryImages: ["https://picsum.photos/seed/basilica-2/800/600", "https://picsum.photos/seed/basilica-3/800/600"],
    rating: 4.9,
    tags: ["oldest church", "religious", "sinulog"],
    coordinates: { lat: 10.2942, lng: 123.9021 },
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Basilica+Minore+del+Santo+Nino",
    isMustVisit: true
  },
  {
    id: 'cebu-cathedral',
    name: "Metropolitan Cebu Cathedral",
    description: "The ecclesiastical seat of the Archdiocese of Cebu, featuring distinct Baroque architecture.",
    overview: "The Metropolitan Cathedral of the Holy Guardian Angels is located just blocks away from the Basilica del Santo Niño. It is a large stone church known for its low-slung, earthquake-proof Baroque design. The exterior features a classic belfry and a pediment decorated with intricate carvings. Inside, visitors will find a serene environment with a modern yet elegant altar and spacious transepts that accommodate the city's largest religious ceremonies.\n\nThe cathedral complex also includes the Archdiocesan Museum and a beautifully landscaped courtyard. Unlike the bustling Basilica, the Cathedral offers a quieter space for reflection. It serves as the primary church for the local Catholic community for weddings, funerals, and major archdiocesan events.",
    significance: "The Cebu Cathedral is significant as the center of religious administration in the Visayas. While construction began in the 17th century, it was frequently interrupted by lack of funds, pirate raids, and eventually sustained heavy damage during WWII. Its survival and subsequent restoration symbolize the persistence of the Cebuano community and their commitment to preserving their religious institutions.\n\nIt serves as a physical record of the growth of the Catholic Church in the region, transitioning from a small mission to a major metropolitan see. The cathedral's architecture is a testament to the localized adaptation of Spanish Baroque styles, intended to withstand the natural calamities common in the Philippines.",
    category: "Churches & Religious Heritage Sites",
    location: "Mabini St, Cebu City",
    city: "Cebu City",
    visitingHours: "5:00 AM - 8:00 PM",
    imageUrl: "https://picsum.photos/seed/cathedral/800/600",
    rating: 4.6,
    tags: ["cathedral", "baroque"],
    coordinates: { lat: 10.2954, lng: 123.9028 },
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Cebu+Metropolitan+Cathedral",
    isMustVisit: false
  },
  {
    id: 'cebu-cross',
    name: "Magellan’s Cross",
    description: "The iconic symbol of Cebu, marking the site where the first Christian cross was planted in 1521.",
    overview: "Magellan's Cross is housed in a small octagonal stone pavilion known as a kiosk, situated right next to the Basilica del Santo Niño and the Cebu City Hall. The kiosk features beautiful ceiling paintings depicting the arrival of Ferdinand Magellan and the baptism of Rajah Humabon and Queen Juana. The central feature is a large wooden cross that is believed to contain the original fragments of the cross planted by Magellan's expedition in 1521.\n\nVisitors can observe the cross from the exterior or step inside the pavilion to appreciate the artwork and history. It is a popular spot for both tourists and locals, often surrounded by traditional candle sellers who offer prayers while performing the 'Sinulog' dance steps. The site is a standard stop for anyone exploring the historical district of downtown Cebu.",
    significance: "This site is arguably the most important historical landmark in Cebu, representing the very moment the Philippines encountered the West and Christianity. It marks the beginning of the Spanish colonial period and the religious transformation of the archipelago. The planting of the cross on April 14, 1521, is considered the formal introduction of the Catholic faith to the Filipino people.\n\nBeyond its religious weight, the cross is a powerful cultural icon that appears in the official seal of Cebu City. It represents the historical identity of Cebu as the 'Cradle of Christianity' in the Philippines. The pavilion itself, built in 1834, is a protected historical structure that has become synonymous with Cebuano heritage.",
    category: "Churches & Religious Heritage Sites",
    location: "P. Burgos St, Cebu City",
    city: "Cebu City",
    visitingHours: "8:00 AM - 6:00 PM",
    imageUrl: "https://picsum.photos/seed/magellan/800/600",
    rating: 4.8,
    tags: ["cross", "magellan"],
    coordinates: { lat: 10.2936, lng: 123.9019 },
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Magellan%27s+Cross",
    isMustVisit: true
  },
  {
    id: 'cebu-arch-museum',
    name: "Archdiocesan Museum of Cebu",
    description: "A museum dedicated to the rich religious and liturgical history of the Cebuano people.",
    overview: "The Archdiocesan Museum is located within the grounds of the Cebu Metropolitan Cathedral. It is housed in the 'bahay na bato' style rectory that once served as the residence for the cathedral's clergy. The museum features several galleries showcasing antique religious icons (santos), silver chalices, ornate priest vestments embroidered with gold thread, and centuries-old church records and documents.\n\nVisitors can explore the evolution of religious art in Cebu and see rare artifacts that are typically hidden in church vaults. The building itself is a highlight, with its polished hardwood floors, wide capiz-shell windows, and coral stone ground floor, offering a glimpse into colonial-era domestic life for the elite clergy.",
    significance: "The museum is significant for preserving the tangible religious heritage of the Visayas. It serves as a repository for the artistic and cultural expressions of the Cebuano people through their faith. Many of the artifacts on display date back to the Spanish colonial period, illustrating the localization of European religious art by Filipino craftsmen.\n\nIt plays a crucial role in education, helping visitors understand the complex history of the Catholic Church in Cebu and its influence on local customs and traditions. The preservation of the building itself is also important as it is one of the few surviving examples of ecclesiastical residences from the late 19th century.",
    category: "Museums & Cultural Institutions",
    location: "Mabini St, Cebu City",
    city: "Cebu City",
    visitingHours: "9:00 AM - 5:00 PM",
    imageUrl: "https://picsum.photos/seed/archmuseum/800/600",
    rating: 4.4,
    tags: ["museum", "religious"],
    coordinates: { lat: 10.2951, lng: 123.9025 },
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Archdiocesan+Museum+of+Cebu",
    isMustVisit: false
  },
  {
    id: 'cebu-gorordo',
    name: "Casa Gorordo Museum",
    description: "A beautifully restored 19th-century residence depicting the lifestyle of the Filipino elite.",
    overview: "Casa Gorordo is a museum located in the historic Parian district of Cebu City. Originally built in the 1850s, it was the home of the Gorordo family, which included Juan Gorordo, the first Filipino Bishop of Cebu. The house is a classic example of the 'Bahay na Bato' architecture, featuring a ground floor made of coral stone and an upper floor of fine Philippine hardwood.\n\nVisitors can take guided tours through the meticulously restored rooms, which are filled with period furniture, antique household items, and personal belongings of the Gorordo family. The museum also features a beautiful garden, a traditional kitchen (cocina), and a cafe. It offers an immersive experience into the sophisticated lifestyle of the mestizo class during the transition from the Spanish to the American colonial eras.",
    significance: "Casa Gorordo is significant as a window into Cebu's social history during the 19th and early 20th centuries. It reflects the cultural synthesis between Spanish, Chinese, and native Filipino influences that defined the elite Parian community. The house is one of the few surviving examples of its kind in Cebu, having escaped the widespread destruction of the city during WWII.\n\nIt is owned and managed by the Ramon Aboitiz Foundation Inc. (RAFI) and serves as a premier cultural institution in the city. The museum not only preserves the physical structure but also promotes the study of Cebuano history and traditions through its exhibits and community programs. It is a National Historical Landmark that stands as a pride of the Parian district.",
    category: "Ancestral Houses & Heritage Residences",
    location: "Lopez Jaena St, Cebu City",
    city: "Cebu City",
    visitingHours: "9:00 AM - 5:00 PM",
    imageUrl: "https://picsum.photos/seed/gorordo/800/600",
    rating: 4.7,
    tags: ["mansion", "lifestyle"],
    coordinates: { lat: 10.2995, lng: 123.9042 },
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Casa+Gorordo+Museum",
    isMustVisit: true
  },
  {
    id: 'cebu-yap-sandiego',
    name: "Yap-Sandiego Ancestral House",
    description: "One of the oldest residential houses in the Philippines, built by Chinese merchants in the 17th century.",
    overview: "The Yap-Sandiego Ancestral House is a unique heritage site located in the Parian district of Cebu City. Built in the late 17th century (around 1675-1700), it is recognized as one of the oldest private homes in the country. The structure is built with coral stones glued with egg whites and features a roof made of heavy 'tisa' tiles. The house is filled with an incredible collection of antiques, including life-sized santos, old glassware, and traditional furniture.\n\nVisitors feel like they are stepping back in time as they walk through the cramped but atmospheric rooms. The house is still owned by the descendants of the original family, and their personal touch is visible in the way the artifacts are displayed. The small garden and the old well add to the charm of this ancient residence.",
    significance: "This house is a rare surviving link to the prosperous Chinese-Filipino merchant community that thrived in Parian centuries ago. It demonstrates the early architectural ingenuity of combining local materials with Chinese construction techniques to create a durable and elegant dwelling. Its survival for over 300 years is a testament to the quality of the materials and the dedication of the family to their heritage.\n\nIt serves as a primary example of the 'parian' lifestyle, where trade and family life were closely intertwined. The Yap-Sandiego house is a major draw for history buffs and photographers, contributing significantly to the cultural tourism of downtown Cebu and the preservation of the Parian's historical identity.",
    category: "Ancestral Houses & Heritage Residences",
    location: "Mabini St, Parian, Cebu City",
    city: "Cebu City",
    visitingHours: "9:00 AM - 6:00 PM",
    imageUrl: "https://picsum.photos/seed/yap/800/600",
    rating: 4.7,
    tags: ["ancestral", "parian"],
    coordinates: { lat: 10.2987, lng: 123.9034 },
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Yap-Sandiego+Ancestral+House",
    isMustVisit: true
  },
  {
    id: 'cebu-jesuit-house',
    name: "1730 Jesuit House",
    description: "A hidden gem dating back to the Jesuit era, tucked inside a modern warehouse.",
    overview: "The 1730 Jesuit House, also known as Museo de Parian, is a fascinating historical site hidden behind the walls of a modern hardware warehouse in the Parian district. As the name suggests, the house dates back to 1730 and served as the residence for the Jesuit superior in Cebu. The house is built on a massive scale, with thick coral stone walls and gigantic hardwood beams that are centuries old.\n\nInside, visitors can see the layers of history revealed through archaeological displays and restored rooms. The museum showcases the house's evolution from a Jesuit residence to a home for prominent local families. It features a unique combination of religious history and secular domestic life, all preserved within a structure that was almost lost to urban development.",
    significance: "The Jesuit House is significant as the oldest dated residential house in the Philippines. It provides a rare look into the early missionary activities of the Jesuits in the Visayas and their influence on local architecture and social structures. The house's location in Parian highlights the historical importance of the district as the center of power and wealth in colonial Cebu.\n\nIts discovery and subsequent conversion into a museum is a success story for heritage preservation. It educates visitors on the 'invisible' history of the city—landmarks that are hidden in plain sight. The museum is a vital part of the Parian heritage trail, offering a deeper understanding of the religious and social dynamics of the 18th century.",
    category: "Ancestral Houses & Heritage Residences",
    location: "Zulueta St, Parian, Cebu City",
    city: "Cebu City",
    visitingHours: "8:30 AM - 5:00 PM",
    imageUrl: "https://picsum.photos/seed/jesuit/800/600",
    rating: 4.8,
    tags: ["jesuit", "oldest"],
    coordinates: { lat: 10.2982, lng: 123.9031 },
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Jesuit+House+Cebu",
    isMustVisit: true
  },
  {
    id: 'cebu-nat-museum',
    name: "National Museum of the Philippines – Cebu",
    description: "The regional branch of the National Museum, housed in the historic Aduana (Customs) Building.",
    overview: "The National Museum of the Philippines – Cebu is located in the beautifully restored Aduana Building, a landmark of American colonial architecture. The building itself is an impressive structure with high ceilings and wide hallways, situated near the Cebu port. The museum features several galleries dedicated to the natural history, archaeology, and ethnography of the Visayas region.\n\nVisitors can see exhibits ranging from pre-colonial burial jars and gold ornaments to modern Visayan art. The museum also showcases the history of the Aduana building itself, which served as a customs house and briefly as the Malacañang sa Sugbo. It is a premier destination for those who want a comprehensive overview of the region's cultural and scientific heritage in a modern museum setting.",
    significance: "This institution is significant as the primary caretaker of the Visayan region's cultural treasures. By housing the museum in the Aduana building, the government has successfully preserved a major architectural landmark while making it accessible to the public. The building's history as a hub for trade and government makes it the perfect site to tell the story of Cebu's connection to the wider world.\n\nThe museum is a key player in the nation's efforts to promote cultural awareness and scientific research. It serves as an educational center for students and a major attraction for tourists, reinforcing Cebu's status as a leading cultural hub in the Philippines. Its presence in the port area revitalizes the historical district and links the city's maritime past with its cultural present.",
    category: "Museums & Cultural Institutions",
    location: "A. Pigafetta St, Cebu City",
    city: "Cebu City",
    visitingHours: "9:00 AM - 6:00 PM",
    imageUrl: "https://picsum.photos/seed/natmuseum/800/600",
    rating: 4.8,
    tags: ["art", "archaeology"],
    coordinates: { lat: 10.2925, lng: 123.9065 },
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=National+Museum+Cebu",
    isMustVisit: true
  },
  {
    id: 'cebu-halad-museum',
    name: "Jose R. Gullas Halad Museum",
    description: "A musically-themed museum that pays tribute to Cebuano composers and musicians.",
    overview: "The Halad Museum is a unique cultural institution located in the downtown area of Cebu City. It is a tribute to the musical heritage of the Cebuano people, specifically honoring the works of local composers from the early to mid-20th century. The museum showcases a collection of vintage musical instruments, original handwritten music scores, and personal memorabilia of famous Cebuano maestros.\n\nVisitors can listen to recordings of classic Cebuano songs and learn about the stories behind the music. The museum's intimate setting and specialized focus make it a must-visit for music lovers and those interested in the artistic side of Cebuano culture. It often hosts small concerts and lectures to keep the musical tradition alive.",
    significance: "The Halad Museum is significant for preserving the distinct musical identity of Cebu. During the 20th century, Cebuano music—particularly the Harana and Kundiman—played a major role in the cultural life of the region. The museum ensures that the contributions of local artists are not forgotten in the age of modern pop music.\n\nIt provides a space for the community to connect with their artistic past and inspires new generations of musicians. By documenting the history of Cebuano compositions, the museum helps maintain a vital part of the city's intangible heritage. It is a labor of love that highlights the deep emotional connection between the Cebuano people and their music.",
    category: "Museums & Cultural Institutions",
    location: "V. Gullas St, Cebu City",
    city: "Cebu City",
    visitingHours: "9:00 AM - 5:00 PM",
    imageUrl: "https://picsum.photos/seed/halad/800/600",
    rating: 4.5,
    tags: ["music", "composers"],
    coordinates: { lat: 10.2974, lng: 123.9051 },
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Jose+R.+Gullas+Halad+Museum",
    isMustVisit: false
  },
  {
    id: 'cebu-usc-museum',
    name: "University of San Carlos Museum",
    description: "A research-oriented museum featuring extensive archaeological and ethnographic collections.",
    overview: "The University of San Carlos (USC) Museum is located within the main campus of one of the oldest universities in Asia. It is a sophisticated museum with four main galleries: Archaeological, Ethnographic, Natural Science, and the Ceramics Gallery. The collections are the result of decades of field research and excavations conducted by the university's faculty and students.\n\nVisitors can see a wide array of artifacts, including pre-colonial pottery, intricate burial jars, ethnographic items from various indigenous groups in the Philippines, and a large collection of biological specimens. The museum is well-curated and provides detailed historical and scientific context for each exhibit, making it an excellent resource for researchers and serious history students.",
    significance: "The USC Museum is a vital institution for understanding the pre-colonial history and biodiversity of the Visayas and Mindanao. It represents the university's long-standing commitment to academic excellence and cultural preservation. The museum's collections have contributed significantly to the national discourse on Filipino identity and heritage.\n\nIt serves as a model for university-based museums in the country, bridging the gap between academic research and public education. By preserving these artifacts, the museum ensures that the deep history of the region is protected for future generations to study and appreciate.",
    category: "Museums & Cultural Institutions",
    location: "P. del Rosario St, Cebu City",
    city: "Cebu City",
    visitingHours: "8:00 AM - 5:00 PM",
    imageUrl: "https://picsum.photos/seed/uscmuseum/800/600",
    rating: 4.6,
    tags: ["university", "anthropology"],
    coordinates: { lat: 10.2992, lng: 123.8992 },
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=USC+Museum+Cebu",
    isMustVisit: false
  },
  {
    id: 'cebu-fort-san-pedro',
    name: "Fort San Pedro",
    description: "The oldest and smallest bastion fort in the Philippines, built by the Spanish in 1565.",
    overview: "Fort San Pedro is a triangular military defense structure located in the Pier Area of Cebu City, right next to Plaza Independencia. Built in 1565 under the command of Miguel Lopez de Legazpi, it is the oldest bastion fort in the Philippines. The fort features three bastions: San Miguel, La Concepcion, and Ignacio de Loyola. Its walls are made of coral stone and lime, standing about 20 feet high.\n\nVisitors can walk along the ramparts, explore the small museum housed inside the former barracks, and enjoy the peaceful gardens within the fort's courtyard. The fort offers a quiet escape from the city's traffic, with benches and shady spots perfect for rest. It is a well-maintained site that provides a clear picture of Spanish military architecture and the defensive strategy of early colonial Cebu.",
    significance: "Historically, Fort San Pedro served as the nucleus of the first Spanish settlement in the Philippines. It was built to protect the settlers from hostile native attacks and later served as a stronghold against pirate raids and other colonial powers. Over the centuries, it has been used as a garrison, a prison, a school, and even a city zoo, reflecting the changing needs of the city.\n\nToday, the fort is a National Historical Landmark and a major tourist destination. It serves as a symbol of Cebu's long and often turbulent history. The preservation of the fort is crucial for maintaining the physical evidence of the city's origins and its role as a strategic gateway for the Spanish Empire in Asia.",
    category: "Historical Landmarks & Monuments",
    location: "A. Pigafetta Street, Cebu City",
    city: "Cebu City",
    visitingHours: "8:00 AM - 7:00 PM",
    imageUrl: "https://picsum.photos/seed/fort/800/600",
    rating: 4.6,
    tags: ["military", "spanish"],
    coordinates: { lat: 10.2924, lng: 123.9056 },
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Fort+San+Pedro",
    isMustVisit: true
  },
  {
    id: 'cebu-heritage-monument',
    name: "Heritage of Cebu Monument",
    description: "A monumental tableau of sculptures depicting major events in the history of Cebu.",
    overview: "The Heritage of Cebu Monument is a massive outdoor sculpture located in the Parian district of Cebu City. Created by national artist Eduardo Castrillo, it was completed in 2000. The monument is a complex tableau made of concrete, bronze, brass, and steel, depicting a timeline of Cebu's history from the pre-colonial era to the modern day. Key scenes include the Battle of Mactan, the baptism of Rajah Humabon, and the building of the Basilica del Santo Niño.\n\nVisitors can walk around the monument to see the different scenes in detail. It is situated on the site of the old Plaza Parian, which was the social and economic heart of the city for centuries. The monument's dynamic and expressive style makes it a striking landmark that is impossible to miss when exploring the Parian heritage trail.",
    significance: "This monument is significant as a visual encyclopedia of Cebuano identity. It consolidates the most pivotal moments of the city's past into a single artistic expression, serving as a point of pride for the local community. By locating it in Parian, the monument revitalizes a district that was historically central to Cebu's growth but had fallen into decline.\n\nIt serves as a powerful educational tool, helping residents and tourists alike to visualize the events that shaped the city. The monument is a centerpiece of Cebu's cultural tourism, representing the spirit of the 'Sugboanon' and their enduring legacy. It is a site where history and art meet to celebrate the heritage of the oldest city in the Philippines.",
    category: "Historical Landmarks & Monuments",
    location: "Sikatuna St, Parian, Cebu City",
    city: "Cebu City",
    visitingHours: "24 Hours",
    imageUrl: "https://picsum.photos/seed/monument/800/600",
    rating: 4.8,
    tags: ["sculpture", "parian"],
    coordinates: { lat: 10.2990, lng: 123.9036 },
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Heritage+of+Cebu+Monument",
    isMustVisit: true
  },
  {
    id: 'cebu-colon-street',
    name: "Colon Street, Obelisk, and Historical Marker",
    description: "The oldest street in the Philippines, established in 1565 by the Spanish expedition.",
    overview: "Colon Street is the oldest national road in the Philippines, located in the heart of downtown Cebu City. It was planned and built in 1565 under the leadership of Miguel Lopez de Legazpi. Today, it is a bustling commercial area lined with shops, department stores, and markets. An obelisk and a historical marker stand at one end of the street to commemorate its founding and its role in the city's history.\n\nVisitors to Colon Street will experience the raw energy of Cebu's commercial life. While much of its original colonial architecture was destroyed during WWII, the street's historical significance is preserved in its name and the commemorative markers. It is a place where history meets the everyday reality of modern urban life, making it a unique and gritty destination for travelers.",
    significance: "Colon Street is significant as the commercial and social axis around which the city of Cebu grew. Named after Christopher Columbus (Cristobal Colon), it was the site of the city's first businesses, schools, and theaters. For centuries, it was the most prestigious address in Cebu, where the elite families and major merchants conducted their affairs.\n\nHistorically, it represents the early Spanish attempt at urban planning in the archipelago. Today, it remains the economic heart of downtown Cebu, serving as a symbol of the city's enduring role as a hub for trade and transport. The historical marker serves as a reminder of the street's long legacy, connecting the modern shopper with the 450-year-old history of the road they are walking on.",
    category: "Historical Landmarks & Monuments",
    location: "Colon St, Cebu City",
    city: "Cebu City",
    visitingHours: "24 Hours",
    imageUrl: "https://picsum.photos/seed/colon/800/600",
    rating: 4.3,
    tags: ["oldest street", "commerce"],
    coordinates: { lat: 10.2983, lng: 123.9038 },
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Colon+Street+Cebu",
    isMustVisit: false
  },
  {
    id: 'cebu-plaza-independencia',
    name: "Plaza Independencia",
    description: "The largest and most important historic park in Cebu City, located near Fort San Pedro.",
    overview: "Plaza Independencia is a large, open public park situated right next to Fort San Pedro and the Cebu Port. It is the green heart of the city's historical district, featuring wide paved paths, century-old acacia trees, and several monuments dedicated to Filipino heroes like Jose Rizal and Miguel Lopez de Legazpi. The park provides a spacious and peaceful environment for walking, jogging, and community gatherings.\n\nVisitors can enjoy the shade of the massive trees, watch the ships in the nearby harbor, or visit the adjacent fort. The plaza is often used for city-wide events, political rallies, and cultural festivals. It is a well-lit and safe area that is popular with both locals and tourists throughout the day and evening.",
    significance: "Plaza Independencia is significant as a silent witness to the various colonial eras of Cebu. It has served as a parade ground for Spanish soldiers, a site for American colonial celebrations, and a place for public protests during the fight for independence. Its name reflects the transition of the Philippines from a colony to a sovereign nation.\n\nCulturally, it is the primary civic space for the people of Cebu. The monuments within the park tell the story of the city's political and intellectual history. The preservation of this large green space in the middle of a dense urban environment is crucial for the community's well-being and for maintaining the integrity of the historical district.",
    category: "Plazas, Parks & Public Spaces",
    location: "M.J. Cuenco Ave, Cebu City",
    city: "Cebu City",
    visitingHours: "24 Hours",
    imageUrl: "https://picsum.photos/seed/independencia/800/600",
    rating: 4.5,
    tags: ["park", "plaza"],
    coordinates: { lat: 10.2928, lng: 123.9050 },
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Plaza+Independencia+Cebu",
    isMustVisit: true
  },
  {
    id: 'cebu-plaza-sugbo',
    name: "Plaza Sugbo",
    description: "A civic plaza located between Cebu City Hall and Magellan's Cross.",
    overview: "Plaza Sugbo is a paved public square situated directly in front of the Cebu City Hall, with Magellan's Cross on its other side. It is the geographic and administrative center of the city's heritage district. The plaza is an open space that offers clear views of the City Hall's facade and the pavilion of Magellan's Cross. It is often the starting point for religious processions and civic parades.\n\nVisitors will find it a convenient place to orient themselves when exploring downtown. The plaza is usually bustling with people visiting the City Hall or the Basilica. It is a clean and organized space that reflects the city government's efforts to highlight its historical landmarks and provide a dignified environment for its citizens.",
    significance: "Plaza Sugbo is significant as the physical link between the city's political power (City Hall) and its spiritual roots (Magellan's Cross). The name 'Sugbo' is the pre-colonial name of Cebu, and the plaza honors this ancient identity. It serves as the primary stage for many of the city's most important public rituals.\n\nHistorically, this area has always been the center of Cebu since its founding. The plaza's design is intended to create a sense of continuity between the past and the present. It is a vital part of the city's urban fabric, facilitating the movement of thousands of people daily through the heart of the historical zone.",
    category: "Plazas, Parks & Public Spaces",
    location: "Magallanes St, Cebu City",
    city: "Cebu City",
    visitingHours: "24 Hours",
    imageUrl: "https://picsum.photos/seed/sugbo/800/600",
    rating: 4.4,
    tags: ["civic", "plaza"],
    coordinates: { lat: 10.2936, lng: 123.9022 },
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Plaza+Sugbo",
    isMustVisit: false
  },
  {
    id: 'cebu-plaza-hamabar',
    name: "Plaza Hamabar",
    description: "A historic plaza named after Rajah Humabon, the first native ruler to embrace Christianity.",
    overview: "Plaza Hamabar is a small, quiet plaza located near the Cebu Metropolitan Cathedral. It features a large statue of Rajah Humabon (also known as Hamabar), the pre-colonial ruler of Cebu who welcomed Magellan's expedition in 1521. The plaza is a simple green space with benches and a few commemorative plaques explaining the ruler's significance.\n\nVisitors can stop by for a brief rest while walking between the Cathedral and the Parian district. It is much less crowded than the nearby Plaza Sugbo, offering a more tranquil environment to reflect on the early history of the city and its pre-colonial leadership.",
    significance: "Plaza Hamabar is significant for honoring the indigenous leadership of Cebu during the arrival of the Spanish. Rajah Humabon played a pivotal role in the early encounters between the two cultures, and his baptism marked the first step in the Christianization of the Philippines. The plaza serves as a reminder that Cebu's history did not begin with the Spanish but was built upon an existing and sophisticated society.\n\nCulturally, the plaza helps maintain the memory of the native chieftains who shaped the early destiny of the island. It is an important site for those interested in the 'other side' of the colonial narrative, providing a dedicated space to celebrate the ancestral heritage of the Cebuano people.",
    category: "Plazas, Parks & Public Spaces",
    location: "Mabini St, Cebu City",
    city: "Cebu City",
    visitingHours: "24 Hours",
    imageUrl: "https://picsum.photos/seed/hamabar/800/600",
    rating: 4.2,
    tags: ["rajah", "plaza"],
    coordinates: { lat: 10.2951, lng: 123.9029 },
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Plaza+Hamabar",
    isMustVisit: false
  },
  {
    id: 'cebu-fuente-circle',
    name: "Fuente Osmeña Circle",
    description: "A historic rotunda and public park that serves as the heart of midtown Cebu City.",
    overview: "Fuente Osmeña Circle is a circular public park and fountain located at the intersection of Osmeña Boulevard and other major roads in midtown Cebu. The park features a landmark fountain built in 1912 to commemorate the city's new water system. It is a green oasis in the middle of a busy commercial district, with wide paths, benches, and manicured gardens.\n\nVisitors will find it a central landmark for navigating the city. During the day, it is a pleasant spot for a stroll or to sit and watch the traffic pass by. At night, especially during the Christmas season and the Sinulog festival, the circle is brilliantly illuminated and becomes a hub for outdoor events, concerts, and night markets. It is the geographic center of the city's social and commercial life outside the downtown area.",
    significance: "Fuente Osmeña is significant as a symbol of the city's modernization and its entry into the 20th century. Named after Sergio Osmeña, the first Filipino Speaker of the House and later President of the Philippines, it honors one of Cebu's greatest sons. The fountain itself represents the city's growth and its ability to provide modern infrastructure for its citizens.\n\nCulturally, the circle is the ground zero for many of Cebu's most important public celebrations. It is a traditional gathering point for student groups, sports enthusiasts, and families. The preservation of this rotunda is vital for the city's identity and its urban layout, linking the old downtown with the growing uptown districts.",
    category: "Plazas, Parks & Public Spaces",
    location: "Osmeña Blvd, Cebu City",
    city: "Cebu City",
    visitingHours: "24 Hours",
    imageUrl: "https://picsum.photos/seed/fuente/800/600",
    rating: 4.4,
    tags: ["fountain", "modern"],
    coordinates: { lat: 10.3113, lng: 123.8925 },
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Fuente+Osmena+Circle",
    isMustVisit: false
  },
  {
    id: 'cebu-city-hall',
    name: "Cebu City Hall",
    description: "The seat of the local government, overlooking Plaza Sugbo and the historical district.",
    overview: "Cebu City Hall is a prominent government building located across from Plaza Sugbo and Magellan's Cross. The current structure is a blend of classical and modern architectural styles, serving as the administrative headquarters for the city. Its location puts it right at the heart of the city's most historic zone, making it a visible symbol of civic authority.\n\nVisitors can appreciate the building's facade from the plaza or enter the lobby to see the various city departments in action. The area around the City Hall is a busy hub of activity, with people from all walks of life conducting official business or exploring the nearby landmarks. It is a landmark that represents the continuity of governance in the Philippines' oldest city.",
    significance: "Cebu City Hall is significant as the modern successor to the centuries-old administrative power that has resided in this spot since the Spanish era. It represents the city's commitment to serving its people while remaining connected to its historical roots. The building's prominent position next to Magellan's Cross highlights the close relationship between the church and the state in Cebuano history.\n\nIt is a site of major political and civic decisions that shape the future of the city. For the residents, it is a symbol of their identity as Sugboanons and a point of pride. The preservation of this area as a dignified civic space is essential for the city's functioning and its historical integrity.",
    category: "Government & Historic Buildings",
    location: "Magallanes St, Cebu City",
    city: "Cebu City",
    visitingHours: "8:00 AM - 5:00 PM",
    imageUrl: "https://picsum.photos/seed/cityhall/800/600",
    rating: 4.5,
    tags: ["civic", "government"],
    coordinates: { lat: 10.2931, lng: 123.9019 },
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Cebu+City+Hall",
    isMustVisit: false
  },
  {
    id: 'cebu-capitol',
    name: "Cebu Provincial Capitol",
    description: "A neoclassical masterpiece and the seat of the provincial government of Cebu.",
    overview: "The Cebu Provincial Capitol is a grand neoclassical building located at the northern end of Osmeña Boulevard in Cebu City. Designed by the renowned Filipino architect Juan Arellano and completed in 1938, it is widely regarded as one of the most beautiful government buildings in the Philippines. The building features massive columns, a grand dome, and two large sculptural groups at the entrance representing the wealth of the province.\n\nVisitors can admire the impressive architecture from the street or walk up the grand steps to the lobby. The interior features high ceilings, polished floors, and historical murals. The Capitol overlooks a large open area and is a popular spot for photography, especially during the sunset when the light hits the white facade. It is the administrative center for the entire province of Cebu.",
    significance: "The Capitol is significant as a masterpiece of American colonial architecture and a symbol of the province's political and economic importance. The inscription on its facade, 'The Authority of the Government Emanates from the People,' reflects the democratic ideals of the Commonwealth era. It stands as a monument to the leadership and heritage of the Cebuano people.\n\nHistorically, it has served as the seat of the provincial government through various periods, including a brief time during WWII when it was occupied by the Japanese. Its preservation is a top priority for the provincial government, serving as a source of pride and a major landmark that defines the northern boundary of the city's core district.",
    category: "Government & Historic Buildings",
    location: "Escario St, Cebu City",
    city: "Cebu City",
    visitingHours: "8:00 AM - 5:00 PM",
    imageUrl: "https://picsum.photos/seed/capitol/800/600",
    rating: 4.8,
    tags: ["capitol", "government"],
    coordinates: { lat: 10.3175, lng: 123.8906 },
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Cebu+Provincial+Capitol",
    isMustVisit: true
  },
  {
    id: 'cebu-patria',
    name: "Patria de Cebu",
    description: "A historic commercial and social building in the heart of the old city district.",
    overview: "Patria de Cebu is a multi-story building located along the historic Colon district in Cebu City. It is a well-known landmark that has served various functions over the decades, including as a recreation center, a dormitory for young Catholics, and a hub for church-based social services. The building features a classic mid-20th-century design and is situated in a busy commercial area near the Basilica and the Cathedral.\n\nVisitors will recognize it by its prominent sign and its location among the bustling shops of downtown. While it is currently undergoing redevelopment, it remains a significant part of the urban landscape. It is a place where many generations of Cebuanos have stayed or gathered for community activities, contributing to the lived history of the downtown area.",
    significance: "Patria de Cebu is significant for its role in the social and religious life of the city. It was established by the church to provide a safe and moral environment for students and workers coming to the city from the provinces. Its history is closely tied to the Archdiocese of Cebu's mission to support the community outside the walls of the church.\n\nCulturally, it represents the era of community-focused urban development and the importance of social institutions in the city's growth. Its redevelopment into a modern complex while preserving its historical character is a major project that highlights the balance between progress and heritage in the oldest district of Cebu.",
    category: "Government & Historic Buildings",
    location: "P. Burgos St, Cebu City",
    city: "Cebu City",
    visitingHours: "8:00 AM - 5:00 PM",
    imageUrl: "https://picsum.photos/seed/patria/800/600",
    rating: 4.1,
    tags: ["landmark", "social"],
    coordinates: { lat: 10.2947, lng: 123.9018 },
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Patria+de+Cebu",
    isMustVisit: false
  },
  {
    id: 'cebu-taoist',
    name: "Cebu Taoist Temple",
    description: "A colorful temple and major cultural landmark for the local Chinese community.",
    overview: "The Cebu Taoist Temple is a magnificent place of worship located in the Beverly Hills subdivision of Cebu City. Built in 1972, the temple sits at an elevation of 300 meters above sea level. It is characterized by its colorful multi-tiered roofs, dragon motifs, and intricate carvings that follow traditional Chinese architectural styles. The complex includes several temples, a small replica of the Great Wall of China, and beautifully landscaped gardens.\n\nVisitors can climb the 81 steps (representing the 81 chapters of Taoist scripture) to reach the main temple and enjoy a panoramic view of Cebu City and Mactan Island. The atmosphere is serene and respectful, as it is still an active place of worship. It is a popular destination for those seeking peace, beautiful architecture, and a wider perspective of the city's cultural diversity.",
    significance: "The Taoist Temple is significant as the primary symbol of the religious and cultural influence of the Chinese-Filipino community in Cebu. It represents the integration of Chinese traditions into the broader Cebuano society. The temple serves as a reminder that Cebu is a melting pot of cultures and that religious diversity is a key part of the city's identity.\n\nCulturally, it is one of the most photographed and visited landmarks in the city. It promotes understanding and respect for non-Christian faiths and provides a space for the local Chinese community to practice their rituals and maintain their heritage. Its elevated position and grand design make it a landmark that is visible from many parts of the city, symbolizing the community's prominent role in Cebu's development.",
    category: "Cultural & Religious (Non-Catholic Sites)",
    location: "Beverly Hills, Cebu City",
    city: "Cebu City",
    visitingHours: "8:00 AM - 5:00 PM",
    imageUrl: "https://picsum.photos/seed/taoist/800/600",
    rating: 4.6,
    tags: ["temple", "chinese"],
    coordinates: { lat: 10.3344, lng: 123.8883 },
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Cebu+Taoist+Temple",
    isMustVisit: true
  },

  // --- TALISAY CITY ---
  {
    id: 'talisay-landing',
    name: "Talisay Landing Site",
    description: "The historic beach where American liberation forces landed in 1945 to free Cebu.",
    overview: "The Talisay Landing Site, located at Larawan Beach, is a major WWII memorial in Talisay City. It features several large statues depicting the American liberation forces wading ashore from their landing crafts on March 26, 1945. The site is an open beach area with a memorial park that includes historical markers and plaques explaining the details of the military operation.\n\nVisitors can see the monument up close and walk along the beach where the actual landing took place. It is a place of reflection, often used for commemorative ceremonies every March. The park offers a scenic view of the sea and serves as a vital historical lesson for those interested in the role of Cebu in the Pacific theater of WWII.",
    significance: "This site is significant as the turning point for the liberation of Cebu from Japanese occupation. The landing of the US Army's Americal Division, supported by local guerrillas, led to the eventual surrender of the Japanese forces on the island. It marks a moment of immense relief and hope for the people of Cebu after years of wartime hardship.\n\nCulturally, the monument honors the bravery of both the Allied soldiers and the Filipino resistance fighters. It is a site of deep patriotic value for the people of Talisay and the entire province. The preservation of the landing site ensures that the sacrifices made for the region's freedom are remembered and honored by future generations.",
    category: "Historical Landmarks & Monuments",
    location: "Larawan Beach, Talisay City",
    city: "Talisay City",
    visitingHours: "24 Hours",
    imageUrl: "https://picsum.photos/seed/landing/800/600",
    rating: 4.4,
    tags: ["WWII", "memorial"],
    coordinates: { lat: 10.2525, lng: 123.8445 },
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Talisay+Landing+Site",
    isMustVisit: true
  },
  {
    id: 'talisay-church',
    name: "Sta. Teresa de Avila Parish Church",
    description: "The historical heart of Talisay, featuring beautiful Spanish colonial architecture.",
    overview: "Sta. Teresa de Avila Parish is the oldest and most important church in Talisay City. It is a fine example of Spanish colonial church architecture, built with thick stone walls and a classic facade. The church interior is spacious and well-lit, with a beautiful main altar and traditional religious art. It is located near the city plaza and the beach area.\n\nVisitors will find it a serene and welcoming space. The church is the center of the city's religious life, hosting daily masses and serving as the focal point for the annual city fiesta in honor of Saint Teresa. It is a cornerstone of the community, providing a sense of historical continuity and spiritual guidance for the people of Talisay.",
    significance: "This church is significant as the spiritual foundation of Talisay. Since its establishment in the mid-19th century, it has been the witness to the city's evolution from a small village to a bustling urban center. The church's architecture reflects the localized adaptation of European religious styles, using indigenous materials like coral stone.\n\nIt plays a major role in maintaining the city's cultural traditions and festivals. The parish is a source of identity and social cohesion for the local population. Its preservation as a historical landmark is essential for protecting the architectural and religious heritage of Talisay City.",
    category: "Churches & Religious Heritage Sites",
    location: "Talisay City",
    city: "Talisay City",
    visitingHours: "5:00 AM - 8:00 PM",
    imageUrl: "https://picsum.photos/seed/talisaychurch/800/600",
    rating: 4.5,
    tags: ["church", "religious"],
    coordinates: { lat: 10.2443, lng: 123.8491 },
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Sta.+Teresa+de+Avila+Parish",
    isMustVisit: false
  },
  {
    id: 'talisay-plaza',
    name: "Talisay City Plaza",
    description: "A historic public square and the center of community life in Talisay.",
    overview: "Talisay City Plaza is a wide open public space located in front of the Sta. Teresa de Avila Church and near the old city hall. It is a traditional Filipino town plaza with paved walks, benches, and a central stage or kiosk. The plaza is surrounded by trees and offers a refreshing space for people to gather and relax.\n\nVisitors will see children playing, students studying, and locals chatting in the park. It is a great place to experience the local lifestyle of Talisay. The plaza is the venue for many city-wide events, such as the Inasal Festival and various civic celebrations. It remains the social heart of the city's downtown district.",
    significance: "The plaza is significant as the primary civic and social space for the people of Talisay. It follows the traditional Spanish town layout where the church, the government, and the public square are all situated together. This spatial arrangement reflects the social structure of the colonial period that has persisted into the present.\n\nCulturally, it is a site of community bonding and shared history. The plaza has hosted countless celebrations, meetings, and historical events over the decades. Its maintenance as a public green space is vital for the quality of life in the city and for preserving the traditional character of Talisay's historical core.",
    category: "Plazas, Parks & Public Spaces",
    location: "Talisay City",
    city: "Talisay City",
    visitingHours: "24 Hours",
    imageUrl: "https://picsum.photos/seed/talisayplaza/800/600",
    rating: 4.2,
    tags: ["park", "plaza"],
    coordinates: { lat: 10.2448, lng: 123.8494 },
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Talisay+City+Plaza",
    isMustVisit: false
  },
  {
    id: 'talisay-hall',
    name: "Talisay City Hall",
    description: "The administrative center of the city, representing its modern growth and governance.",
    overview: "Talisay City Hall is the main government building for the city, located in a sprawling complex that includes various city departments. The building features a modern design that reflects the city's rapid development as a key residential and commercial hub in Metro Cebu. It is situated away from the old downtown area, marking the city's expansion into new districts.\n\nVisitors can see the various offices dedicated to serving the residents of Talisay. The building is usually busy with people processing documents and attending meetings. It is a landmark that represents the administrative efficiency and the future-looking vision of the local government. The grounds are well-maintained and offer a dignified space for civic activities.",
    significance: "Talisay City Hall is significant as the engine of the city's progress. It represents the transition of Talisay from a quiet town to a major component of the Metro Cebu urban sprawl. The building is a symbol of the city's autonomy and its ability to govern its growing population effectively.\n\nHistorically, it stands as the successor to the old municipal buildings that once served the town. It is the site where major policies regarding the city's economy, infrastructure, and culture are made. For the residents, it is a central point of contact with their government and a symbol of their city's pride and potential.",
    category: "Government & Historic Buildings",
    location: "Talisay City",
    city: "Talisay City",
    visitingHours: "8:00 AM - 5:00 PM",
    imageUrl: "https://picsum.photos/seed/talisayhall/800/600",
    rating: 4.3,
    tags: ["civic", "government"],
    coordinates: { lat: 10.2589, lng: 123.8394 },
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Talisay+City+Hall",
    isMustVisit: false
  },

  // --- MANDAUE CITY ---
  {
    id: 'mandaue-st-joseph',
    name: "National Shrine of Saint Joseph",
    description: "A historic church and major pilgrimage site, home to life-sized statues of the Last Supper.",
    overview: "The National Shrine of Saint Joseph, also known as the Mandaue Church, is a historic stone church located in the city center of Mandaue. Established by the Jesuits in the early 17th century, the current structure has undergone several renovations. The church is famous for its unique set of life-sized ivory and wooden statues depicting the Last Supper, which are paraded during the Lenten season.\n\nVisitors will appreciate the church's solemn atmosphere and its beautiful facade. The interior is spacious and traditional, featuring a grand main altar. The shrine is a popular destination for pilgrims and tourists alike, especially during its annual fiesta and the Holy Week. It is a cornerstone of Mandaue's identity and a primary center for the city's religious activities.",
    significance: "This church is significant as one of the oldest parishes in the region, established even before Mandaue became a city. It represents the early missionary efforts to Christianize the agricultural and merchant communities of the area. The shrine status highlights its national importance as a site of devotion to Saint Joseph.\n\nCulturally, the church is the heart of Mandaue's most important traditions. The statues of the Last Supper are a unique artistic and religious treasure that sets this church apart. Its survival through various historical periods, including the colonial and wartime eras, makes it a resilient symbol of the Mandauehanon's faith and heritage.",
    category: "Churches & Religious Heritage Sites",
    location: "P. Burgos St, Mandaue City",
    city: "Mandaue City",
    visitingHours: "6:00 AM - 8:00 PM",
    imageUrl: "https://picsum.photos/seed/mandauechurch/800/600",
    rating: 4.6,
    tags: ["shrine", "religious"],
    coordinates: { lat: 10.3295, lng: 123.9392 },
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=National+Shrine+of+St.+Joseph+Mandaue",
    isMustVisit: true
  },
  {
    id: 'mandaue-sacred-heart',
    name: "Our Lady of the Sacred Heart Church",
    description: "A peaceful monastery and church known for its serene environment and spiritual mission.",
    overview: "Our Lady of the Sacred Heart Church, often associated with the Monastery of the Holy Eucharist, is a significant spiritual center located in Mandaue City. The church features a modern yet spiritually evocative design, emphasizing a quiet and contemplative atmosphere. It is set within a peaceful complex that encourages reflection and prayer, away from the city's industrial noise.\n\nVisitors can attend masses or simply visit the chapel for personal prayer. The church is known for its beautiful music and the dedicated service of the religious community that maintains it. It is a sanctuary for many locals who seek a more intimate and quiet experience of their faith. The well-kept grounds and simple architecture contribute to its overall sense of holiness and peace.",
    significance: "This church is significant for its mission of providing spiritual support and a contemplative space in a highly urbanized and industrial city. It represents the diversity of religious communities and their contribution to the moral and spiritual fabric of Mandaue. The church has become a landmark of faith for its parishioners and a destination for those seeking religious counseling and retreats.\n\nHistorically, it reflects the growth of Mandaue as a city that accommodates both modern development and traditional religious devotion. Its presence adds a layer of spiritual depth to the city's cultural identity, showing that the community values spaces of peace and reflection amidst its economic progress.",
    category: "Churches & Religious Heritage Sites",
    location: "Mandaue City",
    city: "Mandaue City",
    visitingHours: "5:00 AM - 8:00 PM",
    imageUrl: "https://picsum.photos/seed/mandaueheart/800/600",
    rating: 4.4,
    tags: ["church", "religious"],
    coordinates: { lat: 10.3400, lng: 123.9200 },
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Our+Lady+of+the+Sacred+Heart+Mandaue",
    isMustVisit: false
  },
  {
    id: 'mandaue-suico',
    name: "Suico Ancestral House",
    description: "A well-preserved heritage home representing the mid-20th-century residential architecture.",
    overview: "The Suico Ancestral House is a private heritage residence located in Mandaue City. It is an excellent example of the traditional Filipino house design that bridge the gap between the Spanish colonial and American styles. The house features wide windows with capiz shells, high ceilings for natural ventilation, and intricate wooden carvings. It sits on a well-maintained property that reflects the lifestyle of a prominent Mandaue family.\n\nWhile it is a private home, its exterior can be appreciated from the street, and it is a well-known landmark for locals interested in heritage. The house is a reminder of the residential character of Mandaue before it became a major industrial center. It stands as a silent witness to the history and domestic traditions of the city.",
    significance: "The Suico House is significant for its architectural integrity and its role in preserving the domestic heritage of Mandaue. In a city where many old buildings have been replaced by factories and malls, this house is a rare surviving link to the past. It represents the prosperity and cultural sophistication of the city's merchant and landowner class in the early to mid-20th century.\n\nCulturally, it helps maintain the memory of traditional Mandauehanon family life. The house is part of the city's cultural heritage mapping and is recognized for its historical value. Its preservation by the family is a commendable act that contributes to the overall character and historical depth of the city's urban environment.",
    category: "Ancestral Houses & Heritage Residences",
    location: "Mandaue City",
    city: "Mandaue City",
    visitingHours: "9:00 AM - 5:00 PM",
    imageUrl: "https://picsum.photos/seed/suico/800/600",
    rating: 4.2,
    tags: ["ancestral", "residence"],
    coordinates: { lat: 10.3300, lng: 123.9400 },
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Suico+Ancestral+House",
    isMustVisit: false
  },
  {
    id: 'mandaue-cabrera',
    name: "Luis Cabrera Ancestral House and Museum",
    description: "A private heritage home and museum preserving family heirlooms and local records.",
    overview: "The Luis Cabrera Ancestral House is a significant heritage building in Mandaue City that has been partially converted into a museum. The house showcases the architecture and domestic life of a prominent local family from the early 1900s. It contains a wealth of artifacts, including antique furniture, old photographs, personal letters, and traditional household items that tell the story of the family and the city.\n\nVisitors who arrange for a visit can see the meticulously kept rooms and learn about the contributions of the Cabrera family to Mandaue's civic and social life. The house itself is a beautiful example of the 'bahay na bato' style, with its combination of stone and wood. It offers an intimate and personal perspective on the city's history that larger museums cannot provide.",
    significance: "This site is significant as a grassroots effort in heritage preservation. By maintaining their ancestral home and opening it as a museum, the Cabrera family ensures that a part of Mandaue's soul is kept alive. The house serves as a primary source for local history, offering insights into the social dynamics and cultural trends of the past century.\n\nIt is an important educational resource for the community, especially for students studying local history. The museum contributes to the cultural tourism of Mandaue, showing that the city has a rich residential and family-based history alongside its industrial achievements. It is a National Historical Landmark that stands as a testament to the family's dedication to their roots.",
    category: "Ancestral Houses & Heritage Residences",
    location: "Mandaue City",
    city: "Mandaue City",
    visitingHours: "9:00 AM - 5:00 PM",
    imageUrl: "https://picsum.photos/seed/cabrera/800/600",
    rating: 4.3,
    tags: ["museum", "ancestral"],
    coordinates: { lat: 10.3301, lng: 123.9401 },
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Luis+Cabrera+Ancestral+House",
    isMustVisit: false
  },
  {
    id: 'mandaue-library',
    name: "Mandaue City Public Library",
    description: "The city's educational hub, famous for its historic architecture and local archives.",
    overview: "The Mandaue City Public Library is housed in a distinctive building that is a landmark of civic architecture in the city. One of its most famous features is a historic spiral staircase that has been preserved as a centerpiece of the library's design. The library serves as the city's primary repository for books, periodicals, and local historical records.\n\nVisitors can explore the library's collections, use the study areas, or research Mandaue's history in the dedicated archives section. It is a quiet and scholarly environment that is popular with students and researchers. The building's combination of historical charm and modern functionality makes it a unique and valuable space for the community.",
    significance: "The library is significant as the intellectual heart of Mandaue City. It represents the city's commitment to education and the preservation of knowledge. The inclusion of historical archives makes it an essential site for documenting Mandaue's evolution and the achievements of its citizens.\n\nCulturally, the library is a site of community learning and empowerment. The preservation of the building's historical features, like the spiral staircase, shows that the city values its architectural heritage even in its modern public facilities. It is a place where the past is not just stored but used to educate and inspire the future leaders of Mandaue.",
    category: "Museums & Cultural Institutions",
    location: "P. Burgos St, Mandaue City",
    city: "Mandaue City",
    visitingHours: "8:00 AM - 5:00 PM",
    imageUrl: "https://picsum.photos/seed/library/800/600",
    rating: 4.4,
    tags: ["library", "education"],
    coordinates: { lat: 10.3323, lng: 123.9378 },
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Mandaue+City+Public+Library",
    isMustVisit: false
  },
  {
    id: 'mandaue-watchtower',
    name: "Bantayan sa Hari",
    description: "The ruins of a Spanish-era watchtower that once guarded Mandaue from pirate raids.",
    overview: "Bantayan sa Hari is a historical ruin located along the coast of Brgy. Looc in Mandaue City. Built during the Spanish colonial period, it was part of a defensive network of watchtowers designed to warn the city of incoming pirate raids. Today, only the lower portion of the stone tower remains, standing as a weathered but proud witness to the city's maritime history.\n\nVisitors can see the massive coral stone blocks used in its construction and imagine the vigilant soldiers who once scanned the horizon from its top. The site is situated near the Mandaue-Mactan bridge and offers a view of the channel. While it is a small ruin, it is a significant archaeological site that tell a story of survival and protection in a dangerous era.",
    significance: "This watchtower is significant as a rare surviving example of colonial defensive infrastructure in Mandaue. It represents the strategic importance of the city as a target for raids and its early efforts at self-defense. The name 'Bantayan sa Hari' (The King's Watchtower) reflects the tower's role as a protector of the Spanish crown's territory.\n\nHistorically, it is part of a larger system of watchtowers that stretched across the Visayan coastline. Its preservation helps the community remember their ancestors' struggles and their resilience in the face of threats. It is a vital link to Mandaue's maritime past and a unique historical landmark in an area that is now largely industrial.",
    category: "Historical Landmarks & Monuments",
    location: "Looc, Mandaue City",
    city: "Mandaue City",
    visitingHours: "24 Hours",
    imageUrl: "https://picsum.photos/seed/mandauefort/800/600",
    rating: 4.0,
    tags: ["watchtower", "military"],
    coordinates: { lat: 10.3150, lng: 123.9495 },
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Bantayan+sa+Hari+Mandaue",
    isMustVisit: false
  },
  {
    id: 'mandaue-presidencia',
    name: "Mandaue Presidencia",
    description: "The historic city hall building, a symbol of Mandaue's civic identity since 1937.",
    overview: "The Mandaue Presidencia is the historic municipal hall building located in the city center. Completed in 1937 during the American Commonwealth era, it features a distinctive architectural style that blends classical elements with early 20th-century Filipino design. The building is painted in a striking white and sits as a prominent landmark in the city's heritage plaza.\n\nVisitors can see the building's elegant facade and its large open balcony. While most administrative functions have moved to the new legislative building, the Presidencia remains the symbolic heart of Mandaue's governance. The area around it is a pleasant public space used for ceremonies and community gatherings. It is a well-maintained structure that captures the dignity and history of Mandaue's civic life.",
    significance: "The Presidencia is significant as the primary symbol of Mandaue's transition from a town to a city. It was built during a period of great optimism and growth for the Philippines, and its grand design reflects the community's aspirations. It has been the site of countless historical events, from political inaugurations to city festivals.\n\nHistorically, it stands as a monument to the first generations of Mandauehanon leaders who fought for the city's progress. Its preservation is a key part of Mandaue's cultural heritage strategy, serving as a point of pride and a central landmark that defines the city's historical character. It is an icon that appears in many local symbols and remains a beloved part of the urban landscape.",
    category: "Historical Landmarks & Monuments",
    location: "Mandaue City",
    city: "Mandaue City",
    visitingHours: "8:00 AM - 5:00 PM",
    imageUrl: "https://picsum.photos/seed/presidencia/800/600",
    rating: 4.5,
    tags: ["civic", "landmark"],
    coordinates: { lat: 10.3304, lng: 123.9388 },
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Mandaue+Presidencia",
    isMustVisit: true
  },
  {
    id: 'mandaue-bridge',
    name: "Mandaue-Mactan Bridge",
    description: "The first bridge connecting Mactan Island to mainland Cebu, an iconic engineering feat.",
    overview: "The Mandaue-Mactan Bridge, often called the 'First Bridge,' is a massive steel truss bridge that connects Mandaue City to Lapu-Lapu City. Opened in 1970, it was a groundbreaking infrastructure project for its time, spanning the Mactan Channel. The bridge features a high clearance to allow ships to pass underneath and offers wide views of the channel and the surrounding cities.\n\nVisitors can cross the bridge by vehicle or walk along its narrow pedestrian paths for a unique vantage point of the Metro Cebu skyline. The bridge's industrial design has become an iconic part of the city's landscape. It is especially beautiful at night when it is illuminated, serving as a literal and figurative link between the mainland and the island of Mactan.",
    significance: "This bridge is significant as the catalyst for the modern economic boom of Metro Cebu. Before its construction, the only way to reach Mactan was by ferry. The bridge allowed for the rapid development of the Mactan Export Processing Zone, the international airport, and the island's world-class resorts. It transformed Mandaue into a major logistics and industrial hub.\n\nCulturally, the bridge is an icon of progress and connectivity. It represents the shared destiny of the cities of Mandaue, Lapu-Lapu, and Cebu. Its preservation and maintenance are crucial for the continued functioning of the entire metropolitan area. It stands as a monument to Filipino engineering and the region's ability to undertake large-scale projects that benefit the people.",
    category: "Historical Landmarks & Monuments",
    location: "Mandaue City",
    city: "Mandaue City",
    visitingHours: "24 Hours",
    imageUrl: "https://picsum.photos/seed/bridge/800/600",
    rating: 4.6,
    tags: ["bridge", "landmark"],
    coordinates: { lat: 10.3255, lng: 123.9572 },
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Mandaue-Mactan+Bridge",
    isMustVisit: false
  },
  {
    id: 'mandaue-plaza',
    name: "Mandaue City Heritage Plaza",
    description: "A beautifully designed public square that serves as the heart of Mandaue's social life.",
    overview: "Mandaue City Heritage Plaza is the central public square located in the city's downtown district, right in front of the Mandaue Presidencia and the National Shrine of Saint Joseph. The plaza features paved walkways, manicured gardens, and a large central open space. It is a well-lit and organized park that provides a dignified setting for the city's major landmarks.\n\nVisitors will find it a pleasant place to relax, study, or meet friends. The plaza is the primary venue for the city's festivals, particularly the annual fiesta celebration. It is a clean and safe environment that reflects the city government's efforts to provide high-quality public spaces for its citizens. The combination of historical buildings and modern landscaping makes it a beautiful urban focal point.",
    significance: "The plaza is significant as the civic heart of Mandaue City. It follows the traditional Spanish town square model, linking the city's religious center with its political center. This spatial integration is key to the city's historical character and its social functioning. The plaza serves as a site of community bonding and shared public rituals.\n\nCulturally, it represents Mandaue's commitment to preserving its heritage while fostering a vibrant modern community. The plaza's design highlights the historical significance of the surrounding buildings, making it a living museum of the city's past. It is a source of pride for the people of Mandaue and a vital asset for the city's cultural tourism.",
    category: "Plazas, Parks & Public Spaces",
    location: "Mandaue City",
    city: "Mandaue City",
    visitingHours: "24 Hours",
    imageUrl: "https://picsum.photos/seed/mandaueplaza/800/600",
    rating: 4.3,
    tags: ["plaza", "park"],
    coordinates: { lat: 10.3302, lng: 123.9389 },
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Mandaue+City+Heritage+Plaza",
    isMustVisit: false
  },
  {
    id: 'mandaue-leg-building',
    name: "Mandaue Legislative Building",
    description: "The modern administrative center for the city's legislative and council functions.",
    overview: "The Mandaue Legislative Building is a large, modern government facility located near the city center. It houses the offices of the City Council, the Vice Mayor, and various administrative departments. The building features a clean, contemporary design with glass facades and spacious interiors, reflecting the city's role as a major industrial and economic player in the region.\n\nVisitors can see the various halls where the city's laws and policies are debated and passed. The building is part of a larger government complex that marks the city's ongoing modernization. It is a busy hub of civic activity, where the future of Mandaue is actively shaped by its leaders. The grounds are open to the public and provide a glimpse into the functioning of a modern Philippine city.",
    significance: "This building is significant as the symbol of Mandaue's modern governance and democratic processes. It represents the city's growth and its need for specialized facilities to handle the complex administrative tasks of a major urban center. While newer than the Presidencia, it is a landmark that reflects the current era of progress in Mandaue.\n\nHistorically, it stands as the successor to the legislative functions that were once held in the older city hall. It is the site where critical decisions regarding Mandaue's economic development and social services are made. For the citizens, it is a point of engagement with their representatives and a symbol of their city's organized and forward-looking leadership.",
    category: "Government & Historic Buildings",
    location: "Mandaue City",
    city: "Mandaue City",
    visitingHours: "8:00 AM - 5:00 PM",
    imageUrl: "https://picsum.photos/seed/legislative/800/600",
    rating: 4.4,
    tags: ["civic", "government"],
    coordinates: { lat: 10.3308, lng: 123.9395 },
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Mandaue+Legislative+Building",
    isMustVisit: false
  },

  // --- LAPU-LAPU CITY ---
  {
    id: 'llc-regla',
    name: "Virgen de la Regla National Shrine",
    description: "A major pilgrimage site dedicated to the patroness of Lapu-Lapu City.",
    overview: "The Virgen de la Regla National Shrine is a historic stone church located in the heart of the Opon district in Lapu-Lapu City. The shrine is dedicated to Our Lady of the Rule, whose image has been venerated by the locals since the 18th century. The church features a blend of traditional and modern architectural elements, with its current structure designed to accommodate the large number of pilgrims who visit every year.\n\nVisitors can participate in the vibrant religious activities of the parish or visit the side chapel where the sacred image of the Virgin is kept. The shrine is especially crowded in November during the city fiesta, when devotees from all over the country gather to pay homage. The atmosphere is one of deep faith and community spirit, with the church serving as the focal point for the city's social and religious life.",
    significance: "This shrine is significant as the spiritual soul of Lapu-Lapu City. The devotion to the Virgen de la Regla is a defining part of the Oponganon's identity and is deeply woven into their local history and customs. The church's status as a National Shrine recognizes its importance as a center of religious pilgrimage in the Philippines.\n\nCulturally, the shrine is the anchor for many of the city's traditions, including the annual 'regla' procession. It represents the enduring influence of the Catholic faith in the island's development and its role in fostering social cohesion. The preservation of the shrine and its rituals is vital for maintaining the intangible heritage of the people of Mactan.",
    category: "Churches & Religious Heritage Sites",
    location: "B.M. Dimataga St, Lapu-Lapu City",
    city: "Lapu-Lapu City",
    visitingHours: "6:00 AM - 8:00 PM",
    imageUrl: "https://picsum.photos/seed/regla/800/600",
    rating: 4.7,
    tags: ["shrine", "religious", "opon"],
    coordinates: { lat: 10.3103, lng: 123.9494 },
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Virgen+de+la+Regla+Shrine",
    isMustVisit: true
  },
  {
    id: 'llc-mactan-shrine',
    name: "Mactan Shrine (Liberty Shrine)",
    description: "The historic site of the Battle of Mactan, commemorating Lapu-Lapu's victory in 1521.",
    overview: "Mactan Shrine, also known as the Liberty Shrine, is a large historical park located in the Punta Engaño district of Lapu-Lapu City. It marks the site of the historic Battle of Mactan that took place on April 27, 1521. The park features two main landmarks: the Lapu-Lapu Monument, a 20-meter bronze statue of the native chieftain, and the Magellan's Marker, an obelisk built in 1866 to commemorate the site where Ferdinand Magellan fell.\n\nVisitors can explore the open park, walk along the mangrove-lined shore where the battle is believed to have happened, and see the various plaques and murals that tell the story of the first Filipino resistance against foreign rule. The site is a popular destination for tourists and a central location for the city's annual 'Kadaugan sa Mactan' festival, which features a re-enactment of the battle. It is a place of deep historical reflection and national pride.",
    significance: "Mactan Shrine is significant as the symbol of Filipino courage and the first successful resistance against European colonization in Southeast Asia. Lapu-Lapu is honored as the first national hero of the Philippines for defeating the expedition led by Ferdinand Magellan. The site represents the dawn of Philippine history and the enduring spirit of independence.\n\nHistorically, the shrine preserves the memory of a pivotal moment that changed the course of world exploration and colonial history. Culturally, it is a site of immense patriotic value, serving as a reminder of the strength and unity of the early Filipinos. Its preservation as a National Shrine is essential for educating future generations about their roots and the origins of the nation's fight for freedom.",
    category: "Historical Landmarks & Monuments",
    location: "Punta Engaño Rd, Lapu-Lapu City",
    city: "Lapu-Lapu City",
    visitingHours: "24 Hours",
    imageUrl: "https://picsum.photos/seed/mactan/800/600",
    rating: 4.8,
    tags: ["hero", "history", "battle"],
    coordinates: { lat: 10.3347, lng: 124.0150 },
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Mactan+Shrine",
    isMustVisit: true
  },
  {
    id: 'llc-plaza-rizal',
    name: "Plaza Rizal (Rizal Park)",
    description: "The central public plaza of Lapu-Lapu City, honoring the national hero.",
    overview: "Plaza Rizal is the primary public square of Lapu-Lapu City, located in the Opon district near the city's parish church and the old municipal hall. It is a traditional town plaza with a statue of the national hero, Dr. Jose Rizal, at its center. The park features paved walkways, benches, and trees, providing a space for recreation and community interaction.\n\nVisitors will see the plaza as a typical example of Filipino urban planning, where the spiritual, political, and social lives of the town are integrated. It is a busy hub during the day, with students and locals using the space for rest and transit. The plaza is often used for small civic ceremonies and local festivals, maintaining its role as the civic heart of the city's oldest district.",
    significance: "Plaza Rizal is significant as the focal point of community life in Lapu-Lapu City. It represents the city's connection to the national history of the Philippines through its dedication to Jose Rizal. The plaza's layout is a physical record of the traditional Spanish and American town designs that have shaped the urban identity of the country.\n\nCulturally, it serves as a site of social cohesion and public memory. For generations of Oponganons, the plaza has been a place for meeting and celebration. Its preservation is important for maintaining the character of the Opon heritage district and providing a necessary open space in a densely populated urban environment.",
    category: "Plazas, Parks & Public Spaces",
    location: "Lapu-Lapu City",
    city: "Lapu-Lapu City",
    visitingHours: "24 Hours",
    imageUrl: "https://picsum.photos/seed/llcplaza/800/600",
    rating: 4.1,
    tags: ["park", "plaza"],
    coordinates: { lat: 10.3100, lng: 123.9490 },
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Plaza+Rizal+Lapu-Lapu",
    isMustVisit: false
  },
  {
    id: 'llc-millennium-park',
    name: "Millennium Park",
    description: "A waterfront public park offering scenic views of the Mactan Channel.",
    overview: "Millennium Park is a modern waterfront public space located in Lapu-Lapu City, situated along the Mactan Channel with views of the Mandaue-Mactan bridges. The park features open areas for walking, seating spots for relaxing, and a view of the busy maritime traffic in the channel. It is a popular spot for locals to watch the sunset and enjoy the sea breeze.\n\nVisitors will find it a pleasant place for a casual stroll or a picnic. The park is especially active in the late afternoon and evening, when the weather is cooler. It provides a rare public access point to the city's waterfront, offering a wider perspective of the metropolitan area's geography and its connection to the sea.",
    significance: "The park is significant as a symbol of the city's entry into the new millennium and its commitment to providing public recreational spaces. It represents the modernization of Lapu-Lapu's waterfront and the effort to balance urban development with community well-being. Its location highlights the city's maritime identity and its strategic position along the channel.\n\nCulturally, it is a site of modern community life, providing a space for outdoor activities and social interaction. Its preservation as an open waterfront area is important for the city's environmental and social sustainability. It is a landmark that reflects the contemporary aspirations of the people of Lapu-Lapu City.",
    category: "Plazas, Parks & Public Spaces",
    location: "Lapu-Lapu City",
    city: "Lapu-Lapu City",
    visitingHours: "24 Hours",
    imageUrl: "https://picsum.photos/seed/millennium/800/600",
    rating: 4.0,
    tags: ["park", "waterfront"],
    coordinates: { lat: 10.3200, lng: 123.9550 },
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Millennium+Park+Lapu-Lapu",
    isMustVisit: false
  }
];

export function getSiteById(id: string) {
  return HERITAGE_SITES.find(site => site.id === id);
}

export function searchSites(query: string, city?: string, category?: string) {
  return HERITAGE_SITES.filter(site => {
    const matchesQuery = query ? (
      site.name.toLowerCase().includes(query.toLowerCase()) ||
      site.description.toLowerCase().includes(query.toLowerCase()) ||
      site.overview.toLowerCase().includes(query.toLowerCase()) ||
      site.significance.toLowerCase().includes(query.toLowerCase()) ||
      site.tags.some(tag => tag.toLowerCase().includes(query.toLowerCase()))
    ) : true;
    
    // Strict Filtering
    const matchesCity = city && city !== 'All' ? site.city === city : true;
    const matchesCategory = category && category !== 'All' ? site.category === category : true;
    
    return matchesQuery && matchesCity && matchesCategory;
  });
}
